/**
 * SKAT / Erhvervsstyrelsen Standardkontoplanen — Officiel 2026-version
 *
 * Kilde: Standardkontoplanen/JSON/2026-01-01-Standardkontoplan.json
 * Version: 20260101 (gyldig fra 2026-01-01)
 * Repo: https://git.erst.dk/standard-filformater/standard-filformater
 *
 * Denne fil er AUTOMATISK GENERERET fra den officielle JSON.
 * Total: 603 konti (21 hovedkonto + 97 gruppekonto + 485 underkonti)
 * Ranges: 1xxx-3xxx (resultatopgørelse), 5xxx-7xxx (balance), 8xxx (årsafslutning)
 */

import type { StandardAccount, StandardAccountType } from './standard-chart-of-accounts';

/** Officiel versionsangivelse for Standardkontoplanen (til SAF-T <VersionOfStandardAccount>). */
export const STANDARDKONTOPLAN_VERSION = '20260101' as const;

// FSR-suggestions for bestemte standardkonti (til auto-mapping)
const FSR_SUGGESTIONS: Record<number, string[]> = {
  1010: ['4000'],
  1050: ['4200'],
  1100: ['4300'],
  1150: ['4100'],
  1200: ['4100'],
  2000: ['6000'],
  2020: ['6100'],
  2030: ['6100'],
  2110: ['6200'],
  2200: ['7000'],
  2210: ['7000'],
  2400: ['7100'],
  2800: ['7200'],
  3000: ['1000'],
  3010: ['1100'],
  3020: ['1100'],
  3100: ['1200'],
  3200: ['1200'],
  5000: ['3000'],
  5100: ['3000'],
  6500: ['3400'],
  6600: ['3400'],
  7000: ['2000'],
  7100: ['2000'],
  7200: ['2000'],
  7280: ['2000'],
  7300: ['2200'],
  7310: ['2200'],
  7500: ['5600'],
  7600: ['5600'],
  8000: ['8900'],
  8010: ['8900'],
};

// Type-bestemmelse ud fra kontonummer (se header-dokumentation)
function inferType(num: number): StandardAccountType {
  if (num >= 1000 && num <= 3999) {
    if (num >= 3191 && num <= 3999) return 'FINANCIAL';
    return 'EXPENSE';
  }
  if (num >= 5000 && num <= 6499) return 'ASSET';
  if (num >= 6500 && num <= 6999) return 'EQUITY';
  if (num >= 7000 && num <= 7999) return 'LIABILITY';
  if (num >= 8000 && num <= 8999) return 'YEAR_END';
  return 'STATISTICAL';
}

// Alle konti fra den officielle JSON (hovedkonto + gruppekonto + underkonti)
const ALL_ACCOUNTS: Array<{ number: number; name: string; type: StandardAccountType; isHeader: boolean; parentGroup?: number }> = [
  { number: 1000, name: 'RESULTATOPGØRELSE', type: 'EXPENSE', isHeader: true },
  { number: 1001, name: 'Nettoomsætning', type: 'EXPENSE', isHeader: false },
  { number: 1010, name: 'Salg af varer og ydelser', type: 'EXPENSE', isHeader: false, parentGroup: 1001 },
  { number: 1050, name: 'Salg af varer udland, EU', type: 'EXPENSE', isHeader: false, parentGroup: 1001 },
  { number: 1100, name: 'Salg af varer udland, ikke-EU', type: 'EXPENSE', isHeader: false, parentGroup: 1001 },
  { number: 1150, name: 'Salg af ydelser udland, EU', type: 'EXPENSE', isHeader: false, parentGroup: 1001 },
  { number: 1200, name: 'Salg af ydelser udland, ikke-EU', type: 'EXPENSE', isHeader: false, parentGroup: 1001 },
  { number: 1210, name: 'Salgsrabatter', type: 'EXPENSE', isHeader: false, parentGroup: 1001 },
  { number: 1250, name: 'Salgsfragt', type: 'EXPENSE', isHeader: false, parentGroup: 1001 },
  { number: 1300, name: 'Regulering igangværende arbejder', type: 'EXPENSE', isHeader: false, parentGroup: 1001 },
  { number: 1400, name: 'Ændring i lagre af færdigvarer og varer under fremstilling', type: 'EXPENSE', isHeader: false },
  { number: 1410, name: 'Varelagerregulering på lagre af færdigvarer og varer under fremstilling', type: 'EXPENSE', isHeader: false, parentGroup: 1400 },
  { number: 1430, name: 'Nedskrivning på lagre af færdigvarer og varer under fremstilling', type: 'EXPENSE', isHeader: false, parentGroup: 1400 },
  { number: 1450, name: 'Andel af nedskrivning på lagre af færdigvarer og varer under fremstilling (ej fradragsberettiget skattemæssigt)', type: 'EXPENSE', isHeader: false, parentGroup: 1400 },
  { number: 1460, name: 'Øvrige ændringer på lagre af færdigvarer og varer under fremstilling', type: 'EXPENSE', isHeader: false, parentGroup: 1400 },
  { number: 1495, name: 'Arbejde udført for egen regning og opført under aktiver', type: 'EXPENSE', isHeader: false },
  { number: 1496, name: 'Arbejde udført for egen regning og opført under aktiver', type: 'EXPENSE', isHeader: false, parentGroup: 1495 },
  { number: 1500, name: 'Andre driftsindtægter', type: 'EXPENSE', isHeader: false },
  { number: 1510, name: 'Gevinst ved salg af immaterielle anlægsaktiver', type: 'EXPENSE', isHeader: false, parentGroup: 1500 },
  { number: 1530, name: 'Gevinst ved salg af materielle anlægsaktiver', type: 'EXPENSE', isHeader: false, parentGroup: 1500 },
  { number: 1545, name: 'Offentlige tilskud', type: 'EXPENSE', isHeader: false, parentGroup: 1500 },
  { number: 1550, name: 'Øvrige andre driftsindtægter', type: 'EXPENSE', isHeader: false, parentGroup: 1500 },
  { number: 1595, name: 'Eksterne omkostninger', type: 'EXPENSE', isHeader: true },
  { number: 1600, name: 'Omkostninger til råvarer og hjælpematerialer', type: 'EXPENSE', isHeader: false },
  { number: 1610, name: 'Varekøb', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1630, name: 'Varekøb udland, EU', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1650, name: 'Varekøb udland, ikke-EU', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1660, name: 'Ydelseskøb', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1710, name: 'Ydelseskøb udland, EU', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1740, name: 'Ydelseskøb, udland, ikke-EU', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1745, name: 'Underleverandører (varer/ydelser leveret til kunder)', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1760, name: 'Fragtomkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1770, name: 'Varelagerregulering på lagre af råvarer og hjælpematerialer', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1800, name: 'Nedskrivning på varelager', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1801, name: 'Øvrige produktionsomkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1805, name: 'Andel af nedskrivning på varelager (ej fradragsberettiget skattemæssigt)', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1807, name: 'Værdi af eget vareforbrug (kun klasse A)', type: 'EXPENSE', isHeader: false, parentGroup: 1600 },
  { number: 1820, name: 'Andre eksterne omkostninger', type: 'EXPENSE', isHeader: true },
  { number: 1821, name: 'Salgsomkostninger', type: 'EXPENSE', isHeader: false },
  { number: 1850, name: 'Annoncering og reklame', type: 'EXPENSE', isHeader: false, parentGroup: 1821 },
  { number: 1870, name: 'Udstillinger og dekoration', type: 'EXPENSE', isHeader: false, parentGroup: 1821 },
  { number: 1910, name: 'Repræsentationsomkostninger, skattemæssigt begrænset fradrag', type: 'EXPENSE', isHeader: false, parentGroup: 1821 },
  { number: 1930, name: 'Repræsentationsomkostninger, fuld fradragsret skattemæssigt', type: 'EXPENSE', isHeader: false, parentGroup: 1821 },
  { number: 1950, name: 'Andre salgsomkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 1821 },
  { number: 1990, name: 'Gaver og blomster', type: 'EXPENSE', isHeader: false, parentGroup: 1821 },
  { number: 2000, name: 'Rejseomkostninger (salgsomkostning)', type: 'EXPENSE', isHeader: false, parentGroup: 1821 },
  { number: 2020, name: 'Lokaleomkostninger', type: 'EXPENSE', isHeader: false },
  { number: 2030, name: 'Husleje', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2050, name: 'El', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2060, name: 'Elafgift', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2070, name: 'Vand', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2080, name: 'Varme', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2085, name: 'Privat andel el, vand og varme (kun klasse A)', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2090, name: 'Vandafgift', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2100, name: 'Olie- og flaskegasafgift', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2110, name: 'Kulafgift', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2120, name: 'Naturgas- og bygasafgift', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2130, name: 'Co2-afgift', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2140, name: 'Øvrige afgifter', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2150, name: 'Rengøring og renovation (affaldshåndtering)', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2160, name: 'Reparation og vedligeholdelse', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2170, name: 'Reparation og vedligeholdelse, ejendom skattemæssigt afskrivningsberettiget, bygning 1', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2180, name: 'Forsikringer til lokaler og bygninger', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2190, name: 'Ejendomsskatter', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2200, name: 'Andre lokaleomkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 2020 },
  { number: 2220, name: 'Administrationsomkostninger', type: 'EXPENSE', isHeader: false },
  { number: 2230, name: 'Småanskaffelser under skattemæssig grænse for småaktiver', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2240, name: 'Småanskaffelser over skattemæssig grænse for småaktiver', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2255, name: 'Forskningsomkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2260, name: 'Udviklingsomkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2265, name: 'Andel af forskningsomkostninger (berettiget til forhøjet skattemæssigt fradrag)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2266, name: 'Andel af udviklingsomkostninger (berettiget til forhøjet skattemæssigt fradrag)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2280, name: 'Tab på tilgodehavender fra salg og tjenesteydelser', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2290, name: 'Regulering af nedskrivning på tilgodehavender fra salg og tjenesteydelser', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2295, name: 'Andel af regulering af nedskrivning på tilgodehavender fra salg og tjenesteydelser  (ej fradragsberettiget skattemæssigt)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2310, name: 'It-udstyr (hardware, software inkl. licenser og abonnementer)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2350, name: 'Kantineomkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2370, name: 'Kontingenter', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2375, name: 'Aviser og blade', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2380, name: 'Faglitteratur', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2390, name: 'Porto og gebyrer', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2410, name: 'Telefon og internet mv. (kun virksomhed)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2430, name: 'Privat andel / fri-telefon (kun klasse A)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2450, name: 'Kontorartikler', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2460, name: 'Leje og operationelle leasingydelser (ekskl. husleje)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2470, name: 'Rejseomkostninger (administrationsomkostning)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2480, name: 'Vikarassistance', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2510, name: 'Konsulentydelser', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2530, name: 'Leasingomkostninger, personbiler', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2540, name: 'Driftsomkostninger, personbiler', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2548, name: 'Leasingomkostninger, blandet benyttet personbil (kun klasse A)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2550, name: 'Privat andel af biludgifter (kun klasse A)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2560, name: 'Driftsomkostninger, varebiler', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2567, name: 'Leasingomkostninger, blandet benyttet varebil (kun klasse A)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2569, name: 'Leasingomkostninger, varebiler', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2580, name: 'Privat andel af blandet benyttet varebil (kun klasse A)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2620, name: 'Parkeringsomkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2650, name: 'Øvrige forsikringer', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2660, name: 'Offentlige gebyrer og bøder (ej fradragsberettiget skattemæssigt)', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2670, name: 'Revision og regnskabsmæssig assistance', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2680, name: 'Advokatmæssig assistance', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2690, name: 'Øvrige rådgivningshonorarer', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2700, name: 'Ej skattemæssigt fradragsberettigede rådgivningshonorarer', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2710, name: 'Administrationsvederlag/management fee', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2720, name: 'Øreafrunding/kassedifferencer', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2810, name: 'Andre eksterne omkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 2220 },
  { number: 2841, name: 'Personaleomkostninger', type: 'EXPENSE', isHeader: true },
  { number: 2842, name: 'Lønninger', type: 'EXPENSE', isHeader: false },
  { number: 2845, name: 'AM Bidragspligtig A-Indkomst', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2846, name: 'AM Bidragsfri A-Indkomst', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2847, name: 'B-honorar', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2860, name: 'Feriepenge og SH-tillæg', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2865, name: 'Ferietillæg', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2866, name: 'Feriepengeforpligtelse, regulering', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2870, name: 'Jubilæumsgratiale og fratrædelsesgodtgørelse', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2880, name: 'Bestyrelseshonorar', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2885, name: 'Lønrefusioner', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2887, name: 'Personalegoder', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2888, name: 'Fri bil', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2895, name: 'Skattefri rejse- og befordringsgodtgørelse', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2896, name: 'Kursusudgifter', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2897, name: 'ATP, medarbejder', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2898, name: 'ATP, arbejdsgiver', type: 'EXPENSE', isHeader: false, parentGroup: 2842 },
  { number: 2906, name: 'Pensioner', type: 'EXPENSE', isHeader: false },
  { number: 2910, name: 'Pensioner, arbejdsgiver', type: 'EXPENSE', isHeader: false, parentGroup: 2906 },
  { number: 2920, name: 'Vederlag til afløsning af pensionstilsagn', type: 'EXPENSE', isHeader: false, parentGroup: 2906 },
  { number: 2925, name: 'Øvrige pensionsomkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 2906 },
  { number: 2927, name: 'Andre omkostninger til social sikring', type: 'EXPENSE', isHeader: false },
  { number: 2930, name: 'Øvrige omkostninger til social sikring', type: 'EXPENSE', isHeader: false, parentGroup: 2927 },
  { number: 2946, name: 'Lønsumsafgift', type: 'EXPENSE', isHeader: false, parentGroup: 2927 },
  { number: 2947, name: 'Arbejdsskadeforsikringer', type: 'EXPENSE', isHeader: false, parentGroup: 2927 },
  { number: 2991, name: 'Af- og nedskrivninger af materielle og immaterielle anlægsaktiver', type: 'EXPENSE', isHeader: false },
  { number: 3000, name: 'Af- og nedskrivninger af erhvervede immaterielle anlægsaktiver', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3010, name: 'Af- og nedskrivninger af goodwill', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3020, name: 'Af- og nedskrivninger af grunde og bygninger', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3030, name: 'Af- og nedskrivninger af produktionsanlæg og maskiner', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3040, name: 'Af- og nedskrivninger af indretning af lejede lokaler', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3050, name: 'Af- og nedskrivninger af andre anlæg, driftsmateriel og inventar', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3060, name: 'Af- og nedskrivninger af software', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3070, name: 'Af- og nedskrivninger af finansielt leasede grunde og bygninger', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3080, name: 'Af- og nedskrivninger af finansielt leasede produktionsanlæg og maskiner', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3090, name: 'Af- og nedskrivninger af finansielt leasede andre anlæg, driftsmateriel og inventar', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3095, name: 'Privat andel af af- og nedskrivninger (kun klasse A)', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3097, name: 'Gevinst ved salg af andre anlæg, driftsmateriel og inventar blandet benyttet (kun klasse A)', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3099, name: 'Tab ved salg af andre anlæg, driftsmateriel og inventar blandet benyttet (kun klasse A)', type: 'EXPENSE', isHeader: false, parentGroup: 2991 },
  { number: 3120, name: 'Nedskrivning af omsætningsaktiver, som overstiger normale nedskrivninger', type: 'EXPENSE', isHeader: false },
  { number: 3130, name: 'Nedskrivning af omsætningsaktiver, som overstiger normale nedskrivninger', type: 'EXPENSE', isHeader: false, parentGroup: 3120 },
  { number: 3150, name: 'Andre driftsomkostninger', type: 'EXPENSE', isHeader: false },
  { number: 3160, name: 'Tab ved salg af immaterielle anlægsaktiver', type: 'EXPENSE', isHeader: false, parentGroup: 3150 },
  { number: 3165, name: 'Tab ved salg af materielle anlægsaktiver', type: 'EXPENSE', isHeader: false, parentGroup: 3150 },
  { number: 3170, name: 'Øvrige andre driftsomkostninger', type: 'EXPENSE', isHeader: false, parentGroup: 3150 },
  { number: 3180, name: 'Dagsværdiregulering af investeringsejendomme', type: 'EXPENSE', isHeader: false },
  { number: 3185, name: 'Værdireguleringer af investeringsejendomme', type: 'EXPENSE', isHeader: false, parentGroup: 3180 },
  { number: 3191, name: 'Indtægter af kapitalandele i tilknyttede og associerede virksomheder', type: 'FINANCIAL', isHeader: true },
  { number: 3192, name: 'Indtægter af kapitalandele i tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false },
  { number: 3193, name: 'Modtagne udbytter fra tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3192 },
  { number: 3194, name: 'Gevinst ved afhændelse af kapitalandele i tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3192 },
  { number: 3196, name: 'Tab ved afhændelse af kapitalandele i tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3192 },
  { number: 3197, name: 'Nedskrivning af kapitalandele i tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3192 },
  { number: 3198, name: 'Tilbageførsel af nedskrivning af kapitalandele i tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3192 },
  { number: 3200, name: 'Øvrige indtægter af kapitalandele i tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3192 },
  { number: 3210, name: 'Indtægter af kapitalandele i associerede virksomheder', type: 'FINANCIAL', isHeader: false },
  { number: 3211, name: 'Modtagne udbytter fra associerede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3210 },
  { number: 3212, name: 'Gevinst ved afhændelse af kapitalandele i associerede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3210 },
  { number: 3214, name: 'Tab ved afhændelse af kapitalandele i associerede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3210 },
  { number: 3215, name: 'Nedskrivning af kapitalandele i associerede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3210 },
  { number: 3216, name: 'Tilbageførsel af nedskrivning af kapitalandele i associerede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3210 },
  { number: 3217, name: 'Øvrige indtægter af kapitalandele i associerede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3210 },
  { number: 3220, name: 'Indtægter af kapitalinteresser', type: 'FINANCIAL', isHeader: false },
  { number: 3221, name: 'Modtagne udbytter fra kapitalinteresser', type: 'FINANCIAL', isHeader: false, parentGroup: 3220 },
  { number: 3222, name: 'Gevinst ved afhændelse af kapitalinteresser', type: 'FINANCIAL', isHeader: false, parentGroup: 3220 },
  { number: 3224, name: 'Tab ved afhændelse af kapitalinteresser', type: 'FINANCIAL', isHeader: false, parentGroup: 3220 },
  { number: 3225, name: 'Nedskrivning af kapitalinteresser', type: 'FINANCIAL', isHeader: false, parentGroup: 3220 },
  { number: 3226, name: 'Tilbageførsel af nedskrivning af kapitalinteresser', type: 'FINANCIAL', isHeader: false, parentGroup: 3220 },
  { number: 3230, name: 'Øvrige indtægter af kapitalinteresser', type: 'FINANCIAL', isHeader: false, parentGroup: 3220 },
  { number: 3251, name: 'Resultatandele, der hidrører fra tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false },
  { number: 3252, name: 'Resultatandele, der hidrører fra tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3251 },
  { number: 3261, name: 'Resultatandele, der hidrører fra associerede virksomheder', type: 'FINANCIAL', isHeader: false },
  { number: 3262, name: 'Resultatandele, der hidrører fra associerede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3261 },
  { number: 3271, name: 'Resultatandele, der hidrører fra kapitalinteresser', type: 'FINANCIAL', isHeader: false },
  { number: 3272, name: 'Resultatandele, der hidrører fra kapitalinteresser', type: 'FINANCIAL', isHeader: false, parentGroup: 3271 },
  { number: 3370, name: 'Indtægter af andre kapitalandele, værdipapirer og tilgodehavender, der er anlægsaktiver', type: 'FINANCIAL', isHeader: false },
  { number: 3380, name: 'Udbytte fra unoterede porteføljeaktier (bruttoudbytte)', type: 'FINANCIAL', isHeader: false, parentGroup: 3370 },
  { number: 3385, name: 'Kursgevinster af andre kapitalandele, værdipapirer og tilgodehavender, der er anlægsaktiver', type: 'FINANCIAL', isHeader: false, parentGroup: 3370 },
  { number: 3390, name: 'Renteindtægter af andre kapitalandele, værdipapirer og tilgodehavender, der er anlægsaktiver', type: 'FINANCIAL', isHeader: false, parentGroup: 3370 },
  { number: 3395, name: 'Værdiregulering af andre kapitalandele og værdipaprer, der er anlægsaktiver', type: 'FINANCIAL', isHeader: false, parentGroup: 3370 },
  { number: 3400, name: 'Øvrige indtægter af andre kapitalandele, værdipapirer og tilgodehavender, der er anlægsaktiver', type: 'FINANCIAL', isHeader: false, parentGroup: 3370 },
  { number: 3411, name: 'Andre finansielle indtægter fra tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false },
  { number: 3440, name: 'Andre finansielle indtægter fra tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3411 },
  { number: 3445, name: 'Renteindtægter fra tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3411 },
  { number: 3451, name: 'Andre finansielle indtægter', type: 'FINANCIAL', isHeader: false },
  { number: 3470, name: 'Renter fra banker', type: 'FINANCIAL', isHeader: false, parentGroup: 3451 },
  { number: 3490, name: 'Renter vedr. tilgodehavende fra salg af varer og tjenesteydelser', type: 'FINANCIAL', isHeader: false, parentGroup: 3451 },
  { number: 3510, name: 'Rentetillæg mv. fra det offentlige (ej skattepligtig)', type: 'FINANCIAL', isHeader: false, parentGroup: 3451 },
  { number: 3530, name: 'Øvrige finansielle indtægter', type: 'FINANCIAL', isHeader: false, parentGroup: 3451 },
  { number: 3535, name: 'Valutakursregulering (gevinst)', type: 'FINANCIAL', isHeader: false, parentGroup: 3451 },
  { number: 3536, name: 'Værdiregulering af børsnoterede værdipapirer, der er omsætningsaktiver', type: 'FINANCIAL', isHeader: false, parentGroup: 3451 },
  { number: 3537, name: 'Værdiregulering af andre kapitalandele og værdipaprer, der er omsætningsaktiver', type: 'FINANCIAL', isHeader: false, parentGroup: 3451 },
  { number: 3541, name: 'Nedskrivning af finansielle aktiver', type: 'FINANCIAL', isHeader: false },
  { number: 3560, name: 'Nedskrivning af finansielle anlægs- og omsætningsaktiver', type: 'FINANCIAL', isHeader: false, parentGroup: 3541 },
  { number: 3571, name: 'Øvrige finansielle omkostninger', type: 'FINANCIAL', isHeader: true },
  { number: 3572, name: 'Finansielle omkostninger, der hidrører fra tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false },
  { number: 3590, name: 'Finansielle omkostninger, der hidrører fra tilknyttede virksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3572 },
  { number: 3596, name: 'Valutakursreguleringer, udenlandske dattervirksomheder', type: 'FINANCIAL', isHeader: false, parentGroup: 3572 },
  { number: 3601, name: 'Andre finansielle omkostninger', type: 'FINANCIAL', isHeader: false },
  { number: 3610, name: 'Valutakursregulering (tab)', type: 'FINANCIAL', isHeader: false, parentGroup: 3601 },
  { number: 3630, name: 'Kurstab på likvider, bankgæld og prioritetsgæld', type: 'FINANCIAL', isHeader: false, parentGroup: 3601 },
  { number: 3640, name: 'Renter på finansiel leasinggæld', type: 'FINANCIAL', isHeader: false, parentGroup: 3601 },
  { number: 3650, name: 'Renter vedr. leverandører af varer og tjenesteydelser', type: 'FINANCIAL', isHeader: false, parentGroup: 3601 },
  { number: 3670, name: 'Renter til banker og realkreditinstitutter', type: 'FINANCIAL', isHeader: false, parentGroup: 3601 },
  { number: 3675, name: 'Renter til det offentlige (ej fradragsberettiget skattemæssigt)', type: 'FINANCIAL', isHeader: false, parentGroup: 3601 },
  { number: 3690, name: 'Øvrige finansielle omkostninger', type: 'FINANCIAL', isHeader: false, parentGroup: 3601 },
  { number: 3703, name: 'Skat af årets resultat', type: 'FINANCIAL', isHeader: false },
  { number: 3740, name: 'Årets skat (skat af årets skattepligtige indkomst)', type: 'FINANCIAL', isHeader: false, parentGroup: 3703 },
  { number: 3760, name: 'Årets regulering af udskudt skat', type: 'FINANCIAL', isHeader: false, parentGroup: 3703 },
  { number: 3780, name: 'Regulering af skat vedrørende tidligere år', type: 'FINANCIAL', isHeader: false, parentGroup: 3703 },
  { number: 3791, name: 'Andre skatter', type: 'FINANCIAL', isHeader: false },
  { number: 3810, name: 'Andre skatter', type: 'FINANCIAL', isHeader: false, parentGroup: 3791 },
  { number: 5000, name: 'BALANCE', type: 'ASSET', isHeader: true },
  { number: 5001, name: 'AKTIVER', type: 'ASSET', isHeader: true },
  { number: 5002, name: 'Anlægsaktiver', type: 'ASSET', isHeader: true },
  { number: 5003, name: 'Immaterielle anlægsaktiver', type: 'ASSET', isHeader: true },
  { number: 5004, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter', type: 'ASSET', isHeader: false },
  { number: 5010, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter, Kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5004 },
  { number: 5011, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter, Årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5004 },
  { number: 5012, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter, Årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5004 },
  { number: 5015, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter, Intern overførsel til/fra andre poster', type: 'ASSET', isHeader: false, parentGroup: 5004 },
  { number: 5020, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter, opskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5004 },
  { number: 5021, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter, Årets opskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5004 },
  { number: 5022, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter, årets tilbageførsler af tidligere års opskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5004 },
  { number: 5030, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter, Af- og nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5004 },
  { number: 5031, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter, Årets af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5004 },
  { number: 5032, name: 'Færdiggjort udviklingsprojekter, herunder patenter og lignende rettigheder, der stammer fra udviklingsprojekter, Tilbageførte af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5004 },
  { number: 5041, name: 'Erhvervede immaterielle anlægsaktiver', type: 'ASSET', isHeader: false },
  { number: 5042, name: 'Erhvervede immaterielle anlægsaktiver, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5041 },
  { number: 5043, name: 'Erhvervede immaterielle anlægsaktiver, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5041 },
  { number: 5044, name: 'Erhvervede immaterielle anlægsaktiver, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5041 },
  { number: 5050, name: 'Erhvervede immaterielle anlægsaktiver, Opskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5041 },
  { number: 5051, name: 'Erhvervede immaterielle anlægsaktiver, Årets opskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5041 },
  { number: 5052, name: 'Erhvervede immaterielle anlægsaktiver, Tilbageførte opskrivninger fra tidligere år', type: 'ASSET', isHeader: false, parentGroup: 5041 },
  { number: 5055, name: 'Erhvervede immaterielle anlægsaktiver, Af- og nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5041 },
  { number: 5056, name: 'Erhvervede immaterielle anlægsaktiver, årets af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5041 },
  { number: 5057, name: 'Erhvervede immaterielle anlægsaktiver, tilbageførte af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5041 },
  { number: 5061, name: 'Goodwill', type: 'ASSET', isHeader: false },
  { number: 5062, name: 'Goodwill, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5061 },
  { number: 5063, name: 'Goodwill, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5061 },
  { number: 5064, name: 'Goodwill, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5061 },
  { number: 5075, name: 'Goodwill, af- og nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5061 },
  { number: 5076, name: 'Goodwill, årets af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5061 },
  { number: 5077, name: 'Goodwill, tilbageførte afskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5061 },
  { number: 5080, name: 'Udviklingsprojekter under udførelse og forudbetalinger for immaterielle anlægsaktiver', type: 'ASSET', isHeader: false },
  { number: 5085, name: 'Udviklingsprojekter under udførelse og forudbetalinger for immaterielle anlægsaktiver, Kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5080 },
  { number: 5090, name: 'Udviklingsprojekter under udførelse og forudbetalinger for immaterielle anlægsaktiver, Årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5080 },
  { number: 5095, name: 'Udviklingsprojekter under udførelse og forudbetalinger for immaterielle anlægsaktiver, Årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5080 },
  { number: 5100, name: 'Udviklingsprojekter under udførelse og forudbetalinger for immaterielle anlægsaktiver, Intern overførsel til/fra andre poster', type: 'ASSET', isHeader: false, parentGroup: 5080 },
  { number: 5110, name: 'Udviklingsprojekter under udførelse og forudbetalinger for immaterielle anlægsaktiver, Af- og nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5080 },
  { number: 5111, name: 'Udviklingsprojekter under udførelse og forudbetalinger for immaterielle anlægsaktiver, Årets af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5080 },
  { number: 5112, name: 'Udviklingsprojekter under udførelse og forudbetalinger for immaterielle anlægsaktiver, Tilbageførte af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5080 },
  { number: 5142, name: 'Materielle anlægsaktiver', type: 'ASSET', isHeader: true },
  { number: 5150, name: 'Investeringsejendomme', type: 'ASSET', isHeader: false },
  { number: 5160, name: 'Investeringsejendomme, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5150 },
  { number: 5170, name: 'Investeringsejendomme, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5150 },
  { number: 5180, name: 'Investeringsejendomme, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5150 },
  { number: 5185, name: 'Investeringsejendomme, intern overførsel til/fra andre poster', type: 'ASSET', isHeader: false, parentGroup: 5150 },
  { number: 5190, name: 'Investeringsejendomme, årets forbedringer', type: 'ASSET', isHeader: false, parentGroup: 5150 },
  { number: 5200, name: 'Investeringsejendomme, værdireguleringer primo', type: 'ASSET', isHeader: false, parentGroup: 5150 },
  { number: 5201, name: 'Investeringsejendomme, årets værdireguleringer', type: 'ASSET', isHeader: false, parentGroup: 5150 },
  { number: 5205, name: 'Investeringsejendomme, Af- og nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5150 },
  { number: 5210, name: 'Investeringsejendomme, årets af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5150 },
  { number: 5220, name: 'Investeringsejendomme, tilbageførte af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5150 },
  { number: 5231, name: 'Investeringsejendomme under opførelse', type: 'ASSET', isHeader: false },
  { number: 5240, name: 'Investeringsejendomme under opførelse, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5231 },
  { number: 5250, name: 'Investeringsejendomme under opførelse, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5231 },
  { number: 5260, name: 'Investeringsejendomme under opførelse, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5231 },
  { number: 5265, name: 'Investeringsejendomme, intern overførsel til/fra andre poster', type: 'ASSET', isHeader: false, parentGroup: 5231 },
  { number: 5280, name: 'Investeringsejendomme under opførelse, øvrige værdireguleringer primo', type: 'ASSET', isHeader: false, parentGroup: 5231 },
  { number: 5281, name: 'Investeringsejendomme under opførelse, årets værdireguleringer', type: 'ASSET', isHeader: false, parentGroup: 5231 },
  { number: 5282, name: 'Investeringsejendomme under opførelse, nedskrivninger, primo', type: 'ASSET', isHeader: false, parentGroup: 5231 },
  { number: 5290, name: 'Investeringsejendomme under opførelse, årets nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5231 },
  { number: 5300, name: 'Investeringsejendomme under opførelse, tilbageførte nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5231 },
  { number: 5311, name: 'Grunde og bygninger', type: 'ASSET', isHeader: false },
  { number: 5320, name: 'Grunde og bygninger, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5311 },
  { number: 5330, name: 'Grunde og bygninger, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5311 },
  { number: 5340, name: 'Grunde og bygninger, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5311 },
  { number: 5350, name: 'Grunde og bygninger, årets forbedringer', type: 'ASSET', isHeader: false, parentGroup: 5311 },
  { number: 5370, name: 'Grunde og bygninger, værdireguleringer primo', type: 'ASSET', isHeader: false, parentGroup: 5311 },
  { number: 5371, name: 'Grunde og bygninger, årets værdireguleringer', type: 'ASSET', isHeader: false, parentGroup: 5311 },
  { number: 5372, name: 'Grunde og bygninger, Af- og nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5311 },
  { number: 5390, name: 'Grunde og bygninger, årets af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5311 },
  { number: 5400, name: 'Grunde og bygninger, tilbageførte af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5311 },
  { number: 5411, name: 'Produktionsanlæg og maskiner', type: 'ASSET', isHeader: false },
  { number: 5420, name: 'Produktionsanlæg og maskiner, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5411 },
  { number: 5430, name: 'Produktionsanlæg og maskiner, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5411 },
  { number: 5440, name: 'Produktionsanlæg og maskiner, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5411 },
  { number: 5450, name: 'Produktionsanlæg og maskiner, Værdireguleringer primo', type: 'ASSET', isHeader: false, parentGroup: 5411 },
  { number: 5451, name: 'Produktionsanlæg og maskiner, Årets værdireguleringer', type: 'ASSET', isHeader: false, parentGroup: 5411 },
  { number: 5452, name: 'Produktionsanlæg og maskiner, Af- og nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5411 },
  { number: 5470, name: 'Produktionsanlæg og maskiner, årets af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5411 },
  { number: 5480, name: 'Produktionsanlæg og maskiner, tilbageførte af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5411 },
  { number: 5491, name: 'Indretning af lejede lokaler', type: 'ASSET', isHeader: false },
  { number: 5500, name: 'Indretning af lejede lokaler, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5491 },
  { number: 5510, name: 'Indretning af lejede lokaler, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5491 },
  { number: 5520, name: 'Indretning af lejede lokaler, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5491 },
  { number: 5530, name: 'Indretning af lejede lokaler, Værdireguleringer primo', type: 'ASSET', isHeader: false, parentGroup: 5491 },
  { number: 5531, name: 'Indretning af lejede lokaler, Årets værdireguleringer', type: 'ASSET', isHeader: false, parentGroup: 5491 },
  { number: 5532, name: 'Indretning af lejede lokaler, Af- og nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5491 },
  { number: 5540, name: 'Indretning af lejede lokaler, årets af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5491 },
  { number: 5550, name: 'Indretning af lejede lokaler, tilbageførte af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5491 },
  { number: 5561, name: 'Andre anlæg, driftsmateriel og inventar', type: 'ASSET', isHeader: false },
  { number: 5570, name: 'Andre anlæg, driftsmateriel og inventar, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5561 },
  { number: 5580, name: 'Andre anlæg, driftsmateriel og inventar, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5561 },
  { number: 5590, name: 'Andre anlæg, driftsmateriel og inventar, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5561 },
  { number: 5600, name: 'Andre anlæg, driftsmateriel og inventar, Værdireguleringer primo', type: 'ASSET', isHeader: false, parentGroup: 5561 },
  { number: 5601, name: 'Andre anlæg, driftsmateriel og inventar, Årets værdireguleringer', type: 'ASSET', isHeader: false, parentGroup: 5561 },
  { number: 5602, name: 'Andre anlæg, driftsmateriel og inventar, Af- og nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5561 },
  { number: 5610, name: 'Andre anlæg, driftsmateriel og inventar, årets af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5561 },
  { number: 5620, name: 'Andre anlæg, driftsmateriel og inventar, tilbageførte af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5561 },
  { number: 5631, name: 'Materielle anlægsaktiver under udførelse og forudbetalinger for materielle anlægsaktiver', type: 'ASSET', isHeader: false },
  { number: 5640, name: 'Materielle anlægsaktiver under udførelse og forudbetalinger for materielle anlægsaktiver, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5631 },
  { number: 5650, name: 'Materielle anlægsaktiver under udførelse og forudbetalinger for materielle anlægsaktiver, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5631 },
  { number: 5660, name: 'Materielle anlægsaktiver under udførelse og forudbetalinger for materielle anlægsaktiver, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5631 },
  { number: 5670, name: 'Materielle anlægsaktiver under udførelse og forudbetalinger for materielle anlægsaktiver, værdireguleringer primo', type: 'ASSET', isHeader: false, parentGroup: 5631 },
  { number: 5671, name: 'Materielle anlægsaktiver under udførelse og forudbetalinger for materielle anlægsaktiver, årets værdireguleringer', type: 'ASSET', isHeader: false, parentGroup: 5631 },
  { number: 5675, name: 'Materielle anlægsaktiver under udførelse og forudbetalinger for materielle anlægsaktiver, nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5631 },
  { number: 5676, name: 'Materielle anlægsaktiver under udførelse og forudbetalinger for materielle anlægsaktiver, årets nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5631 },
  { number: 5677, name: 'Materielle anlægsaktiver under udførelse og forudbetalinger for materielle anlægsaktiver, tilbageførte nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5631 },
  { number: 5681, name: 'Andre anlæg, driftsmateriel og inventar blandet benyttet (kun klasse A)', type: 'ASSET', isHeader: false },
  { number: 5682, name: 'Andre anlæg, driftsmateriel og inventar blandet benyttet, kostpris primo (kun klasse A)', type: 'ASSET', isHeader: false, parentGroup: 5681 },
  { number: 5683, name: 'Andre anlæg, driftsmateriel og inventar blandet benyttet, Årets tilgange (kun klasse A)', type: 'ASSET', isHeader: false, parentGroup: 5681 },
  { number: 5684, name: 'Andre anlæg, driftsmateriel og inventar blandet benyttet, Årets afgange (kun klasse A)', type: 'ASSET', isHeader: false, parentGroup: 5681 },
  { number: 5685, name: 'Andre anlæg, driftsmateriel og inventar blandet benyttet, Værdireguleringer primo (kun klasse A)', type: 'ASSET', isHeader: false, parentGroup: 5681 },
  { number: 5686, name: 'Andre anlæg, driftsmateriel og inventar blandet benyttet, Årets værdireguleringer (kun klasse A)', type: 'ASSET', isHeader: false, parentGroup: 5681 },
  { number: 5687, name: 'Andre anlæg, driftsmateriel og inventar blandet benyttet, Af- og nedskrivninger primo (kun klasse A)', type: 'ASSET', isHeader: false, parentGroup: 5681 },
  { number: 5688, name: 'Andre anlæg, driftsmateriel og inventar blandet benyttet, Årets af- og nedskrivninger (kun klasse A)', type: 'ASSET', isHeader: false, parentGroup: 5681 },
  { number: 5689, name: 'Andre anlæg, driftsmateriel og inventar blandet benyttet, tilbageførte af- og nedskrivninger (kun klasse A)', type: 'ASSET', isHeader: false, parentGroup: 5681 },
  { number: 5690, name: 'Andre anlæg, driftsmateriel og inventar blandet benyttet, Gevinst og tab (kun klasse A)', type: 'ASSET', isHeader: false, parentGroup: 5681 },
  { number: 5701, name: 'Finansielt leasede aktiver', type: 'ASSET', isHeader: false },
  { number: 5710, name: 'Finansielt leasede aktiver, Kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5701 },
  { number: 5720, name: 'Finansielt leasede aktiver, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5701 },
  { number: 5730, name: 'Finansielt leasede aktiver, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5701 },
  { number: 5740, name: 'Finansielt leasede aktiver, værdireguleringer primo', type: 'ASSET', isHeader: false, parentGroup: 5701 },
  { number: 5741, name: 'Finansielt leasede aktiver, årets værdireguleringer', type: 'ASSET', isHeader: false, parentGroup: 5701 },
  { number: 5745, name: 'Finansielt leasede aktiver, af- og nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5701 },
  { number: 5750, name: 'Finansielt leasede aktiver, årets af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5701 },
  { number: 5760, name: 'Finansielt leasede aktiver, tilbageførte af- og nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5701 },
  { number: 5772, name: 'Finansielle anlægsaktiver', type: 'ASSET', isHeader: true },
  { number: 5773, name: 'Kapitalandele i tilknyttede virksomheder', type: 'ASSET', isHeader: false },
  { number: 5800, name: 'Kapitalandele i tilknyttede virksomheder, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5773 },
  { number: 5810, name: 'Kapitalandele i tilknyttede virksomheder, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5773 },
  { number: 5820, name: 'Kapitalandele i tilknyttede virksomheder, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5773 },
  { number: 5825, name: 'Kapitalandele i tilknyttede virksomheder, intern overførsel til/fra andre poster', type: 'ASSET', isHeader: false, parentGroup: 5773 },
  { number: 5829, name: 'Kapitalandele i tilknyttede virksomheder, opskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5773 },
  { number: 5830, name: 'Kapitalandele i tilknyttede virksomheder, årets opskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5773 },
  { number: 5831, name: 'Kapitalandele i tilknyttede virksomheder, årets tilbageførsler af tidligere års opskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5773 },
  { number: 5835, name: 'Kapitalandele i tilknyttede virksomheder, nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5773 },
  { number: 5836, name: 'Kapitalandele i tilknyttede virksomheder, årets nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5773 },
  { number: 5837, name: 'Kapitalandele i tilknyttede virksomheder, årets tilbageførsler af tidligere års nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5773 },
  { number: 5841, name: 'Tilgodehavender hos tilknyttede virksomheder (anlægsaktiv)', type: 'ASSET', isHeader: false },
  { number: 5842, name: 'Tilgodehavender hos tilknyttede virksomheder (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5841 },
  { number: 5843, name: 'Tilgodehavender hos tilknyttede virksomheder, nedskrivninger primo (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5841 },
  { number: 5844, name: 'Tilgodehavender hos tilknyttede virksomheder, nedskrivninger i årets løb (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5841 },
  { number: 5845, name: 'Tilgodehavender hos tilknyttede virksomheder, tilbageførsel af tidligere års nedskrivninger (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5841 },
  { number: 5851, name: 'Kapitalandele i associerede virksomheder', type: 'ASSET', isHeader: false },
  { number: 5852, name: 'Kapitalandele i associerede virksomheder, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5851 },
  { number: 5853, name: 'Kapitalandele i associerede virksomheder, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5851 },
  { number: 5854, name: 'Kapitalandele i associerede virksomheder, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5851 },
  { number: 5855, name: 'Kapitalandele i associerede virksomheder, intern overførsel til/fra andre poster', type: 'ASSET', isHeader: false, parentGroup: 5851 },
  { number: 5860, name: 'Kapitalandele i associerede virksomheder, opskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5851 },
  { number: 5861, name: 'Kapitalandele i associerede virksomheder, årets opskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5851 },
  { number: 5862, name: 'Kapitalandele i associerede virksomheder, årets tilbageførsler af tidligere års opskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5851 },
  { number: 5870, name: 'Kapitalandele i associerede virksomheder, nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5851 },
  { number: 5871, name: 'Kapitalandele i associerede virksomheder, årets nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5851 },
  { number: 5872, name: 'Kapitalandele i associerede virksomheder, årets tilbageførsler af tidligere års nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5851 },
  { number: 5881, name: 'Tilgodehavender hos associerede virksomheder (anlægsaktiv)', type: 'ASSET', isHeader: false },
  { number: 5882, name: 'Tilgodehavender hos associerede virksomheder (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5881 },
  { number: 5883, name: 'Tilgodehavender hos associerede virksomheder, nedskrivninger primo (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5881 },
  { number: 5884, name: 'Tilgodehavender hos associerede virksomheder, nedskrivninger i årets løb (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5881 },
  { number: 5885, name: 'Tilgodehavender hos associerede virksomheder, tilbageførsel af tidligere års nedskrivninger (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5881 },
  { number: 5891, name: 'Kapitalinteresser', type: 'ASSET', isHeader: false },
  { number: 5900, name: 'Kapitalinteresser, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 5891 },
  { number: 5910, name: 'Kapitalinteresser, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 5891 },
  { number: 5920, name: 'Kapitalinteresser, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 5891 },
  { number: 5925, name: 'Kapitalinteresser, intern overførsel til/fra andre poster', type: 'ASSET', isHeader: false, parentGroup: 5891 },
  { number: 5929, name: 'Kapitalinteresser, opskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5891 },
  { number: 5930, name: 'Kapitalinteresser, årets opskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5891 },
  { number: 5931, name: 'Kapitalinteresser, årets tilbageførsler af tidligere års opskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5891 },
  { number: 5935, name: 'Kapitalinteresser, nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 5891 },
  { number: 5940, name: 'Kapitalinteresser, årets nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5891 },
  { number: 5950, name: 'Kapitalinteresser, årets tilbageførsler af tidligere års nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 5891 },
  { number: 5961, name: 'Tilgodehavender hos kapitalinteresser (anlægsaktiv)', type: 'ASSET', isHeader: false },
  { number: 5970, name: 'Tilgodehavender hos kapitalinteresser (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5961 },
  { number: 5980, name: 'Tilgodehavender hos kapitalinteresser, nedskrivninger primo (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5961 },
  { number: 5984, name: 'Tilgodehavender hos kapitalinteresser, nedskrivninger i årets løb (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5961 },
  { number: 5985, name: 'Tilgodehavender hos kapitalinteresser, tilbageførsel af tidligere års nedskrivninger (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 5961 },
  { number: 5991, name: 'Andre værdipapirer og kapitalandele', type: 'ASSET', isHeader: false },
  { number: 6000, name: 'Andre værdipapirer og kapitalandele', type: 'ASSET', isHeader: false, parentGroup: 5991 },
  { number: 6011, name: 'Andre tilgodehavender (anlægsaktiv)', type: 'ASSET', isHeader: false },
  { number: 6020, name: 'Udskudte skatteaktiver (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6011 },
  { number: 6030, name: 'Øvrige tilgodehavender (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6011 },
  { number: 6040, name: 'Deposita (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6011 },
  { number: 6051, name: 'Tilgodehavender hos virksomhedsdeltagere og ledelse (anlægsaktiv)', type: 'ASSET', isHeader: false },
  { number: 6061, name: 'Tilgodehavender hos direktionen (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6051 },
  { number: 6062, name: 'Tilgodehavender hos bestyrelsen (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6051 },
  { number: 6063, name: 'Tilgodehavender hos tilsynsråd (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6051 },
  { number: 6064, name: 'Tilgodehavender hos repræsentantskab (anlægsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6051 },
  { number: 6073, name: 'Omsætningsaktiver', type: 'ASSET', isHeader: true },
  { number: 6074, name: 'Varebeholdninger', type: 'ASSET', isHeader: true },
  { number: 6075, name: 'Råvarer og hjælpematerialer', type: 'ASSET', isHeader: false },
  { number: 6080, name: 'Råvarer og hjælpematerialer, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 6075 },
  { number: 6081, name: 'Råvarer og hjælpematerialer, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 6075 },
  { number: 6082, name: 'Råvarer og hjælpematerialer, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 6075 },
  { number: 6083, name: 'Råvarer og hjælpematerialer, intern overførsel til/fra andre poster', type: 'ASSET', isHeader: false, parentGroup: 6075 },
  { number: 6085, name: 'Råvarer og hjælpematerialer, nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 6075 },
  { number: 6090, name: 'Råvarer og hjælpematerialer, årets nedskrivning', type: 'ASSET', isHeader: false, parentGroup: 6075 },
  { number: 6091, name: 'Råvarer og hjælpematerialer, tilbageførsel af tidligere års nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 6075 },
  { number: 6101, name: 'Varer under fremstilling', type: 'ASSET', isHeader: false },
  { number: 6110, name: 'Varer under fremstilling, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 6101 },
  { number: 6111, name: 'Varer under fremstilling, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 6101 },
  { number: 6112, name: 'Varer under fremstilling, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 6101 },
  { number: 6113, name: 'Varer under fremstilling, intern overførsel til/fra andre poster', type: 'ASSET', isHeader: false, parentGroup: 6101 },
  { number: 6115, name: 'Varer under fremstilling, nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 6101 },
  { number: 6120, name: 'Varer under fremstilling, årets nedskrivning', type: 'ASSET', isHeader: false, parentGroup: 6101 },
  { number: 6121, name: 'Varer under fremstilling, tilbageførsel af tidligere års nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 6101 },
  { number: 6131, name: 'Fremstillede varer og handelsvarer', type: 'ASSET', isHeader: false },
  { number: 6140, name: 'Fremstillede varer og handelsvarer, kostpris primo', type: 'ASSET', isHeader: false, parentGroup: 6131 },
  { number: 6141, name: 'Fremstillede varer og handelsvarer, årets tilgange', type: 'ASSET', isHeader: false, parentGroup: 6131 },
  { number: 6142, name: 'Fremstillede varer og handelsvarer, årets afgange', type: 'ASSET', isHeader: false, parentGroup: 6131 },
  { number: 6143, name: 'Fremstillede varer og handelsvarer, intern overførsel til/fra andre poster', type: 'ASSET', isHeader: false, parentGroup: 6131 },
  { number: 6145, name: 'Fremstillede varer og handelsvarer, nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 6131 },
  { number: 6150, name: 'Fremstillede varer og handelsvarer, årets nedskrivning', type: 'ASSET', isHeader: false, parentGroup: 6131 },
  { number: 6151, name: 'Fremstillede varer og handelsvarer, tilbageførsel af tidligere års nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 6131 },
  { number: 6161, name: 'Forudbetalinger for varer', type: 'ASSET', isHeader: false },
  { number: 6170, name: 'Forudbetalinger for varer', type: 'ASSET', isHeader: false, parentGroup: 6161 },
  { number: 6182, name: 'Tilgodehavender', type: 'ASSET', isHeader: true },
  { number: 6183, name: 'Tilgodehavender fra salg og tjenesteydelser', type: 'ASSET', isHeader: false },
  { number: 6190, name: 'Tilgodehavender fra salg og tjenesteydelser', type: 'ASSET', isHeader: false, parentGroup: 6183 },
  { number: 6200, name: 'Tilgodehavender fra salg og tjenesteydelser, nedskrivninger primo', type: 'ASSET', isHeader: false, parentGroup: 6183 },
  { number: 6201, name: 'Nedskrivninger i årets løb', type: 'ASSET', isHeader: false, parentGroup: 6183 },
  { number: 6202, name: 'Tilbageførsel af tidligere års nedskrivninger', type: 'ASSET', isHeader: false, parentGroup: 6183 },
  { number: 6231, name: 'Igangværende arbejder for fremmed regning', type: 'ASSET', isHeader: false },
  { number: 6240, name: 'Igangværende arbejder for fremmed regning', type: 'ASSET', isHeader: false, parentGroup: 6231 },
  { number: 6251, name: 'Tilgodehavender hos tilknyttede virksomheder (omsætningsaktiv)', type: 'ASSET', isHeader: false },
  { number: 6252, name: 'Tilgodehavender hos tilknyttede virksomheder (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6251 },
  { number: 6255, name: 'Tilgodehavender hos tilknyttede virksomheder, nedskrivninger primo (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6251 },
  { number: 6256, name: 'Tilgodehavender hos tilknyttede virksomheder, nedskrivninger i årets løb', type: 'ASSET', isHeader: false, parentGroup: 6251 },
  { number: 6257, name: 'Tilgodehavender hos tilknyttede virksomheder, tilbageførsel af tidligere års nedskrivninger (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6251 },
  { number: 6261, name: 'Tilgodehavender hos associerede virksomheder (omsætningsaktiv)', type: 'ASSET', isHeader: false },
  { number: 6262, name: 'Tilgodehavender hos associerede virksomheder (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6261 },
  { number: 6265, name: 'Tilgodehavender hos associerede virksomheder, nedskrivninger primo (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6261 },
  { number: 6266, name: 'Tilgodehavender hos associerede virksomheder, nedskrivninger i årets løb (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6261 },
  { number: 6267, name: 'Tilgodehavender hos associerede virksomheder, tilbageførsel af tidligere års nedskrivninger (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6261 },
  { number: 6281, name: 'Tilgodehavender hos kapitalinteresser (omsætningsaktiv)', type: 'ASSET', isHeader: false },
  { number: 6282, name: 'Tilgodehavender hos kapitalinteresser (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6281 },
  { number: 6285, name: 'Tilgodehavender hos kapitalinteresser, nedskrivninger primo (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6281 },
  { number: 6286, name: 'Tilgodehavender hos kapitalinteresser, nedskrivninger i årets løb (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6281 },
  { number: 6287, name: 'Tilgodehavender hos kapitalinteresser, tilbageførsel af tidligere års nedskrivninger (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6281 },
  { number: 6301, name: 'Andre tilgodehavender (omsætningsaktiv)', type: 'ASSET', isHeader: false },
  { number: 6305, name: 'Udskudte skatteaktiver (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6301 },
  { number: 6310, name: 'Tilgodehavende kildeskat (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6301 },
  { number: 6315, name: 'Tilgodehavende selskabsskat (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6301 },
  { number: 6320, name: 'Tilgodehavende moms (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6301 },
  { number: 6330, name: 'Øvrige tilgodehavender (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6301 },
  { number: 6341, name: 'Krav på indbetaling af virksomhedskapital og overkurs', type: 'ASSET', isHeader: false },
  { number: 6350, name: 'Krav på indbetaling af virksomhedskapital og overkurs', type: 'ASSET', isHeader: false, parentGroup: 6341 },
  { number: 6361, name: 'Tilgodehavender hos virksomhedsdeltagere og ledelse (omsætningsaktiv)', type: 'ASSET', isHeader: false },
  { number: 6365, name: 'Tilgodehavender hos direktionen (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6361 },
  { number: 6370, name: 'Tilgodehavender hos bestyrelsens (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6361 },
  { number: 6375, name: 'Tilgodehavender hos tilsynsråd (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6361 },
  { number: 6376, name: 'Tilgodehavender hos repræsentantskab (omsætningsaktiv)', type: 'ASSET', isHeader: false, parentGroup: 6361 },
  { number: 6381, name: 'Periodeafgrænsningsposter', type: 'ASSET', isHeader: false },
  { number: 6390, name: 'Periodeafgrænsningsposter, der kan opretholdes skattemæssigt', type: 'ASSET', isHeader: false, parentGroup: 6381 },
  { number: 6400, name: 'Periodeafgrænsningsposter, der ikke kan opretholdes skattemæssigt', type: 'ASSET', isHeader: false, parentGroup: 6381 },
  { number: 6412, name: 'Værdipapirer og kapitalandele', type: 'ASSET', isHeader: true },
  { number: 6413, name: 'Kapitalandele i tilknyttede virksomheder', type: 'ASSET', isHeader: false },
  { number: 6420, name: 'Kapitalandele i tilknyttede virksomheder som ikke er bestemt til vedvarende eje', type: 'ASSET', isHeader: false, parentGroup: 6413 },
  { number: 6431, name: 'Andre værdipapirer og kapitalandele', type: 'ASSET', isHeader: false },
  { number: 6450, name: 'Andre værdipapirer og kapitalandele som ikke er bestemt til vedvarende eje', type: 'ASSET', isHeader: false, parentGroup: 6431 },
  { number: 6462, name: 'Likvide beholdninger', type: 'ASSET', isHeader: false },
  { number: 6470, name: 'Likvide beholdninger', type: 'ASSET', isHeader: false, parentGroup: 6462 },
  { number: 6480, name: 'Bankkonto', type: 'ASSET', isHeader: false, parentGroup: 6462 },
  { number: 6500, name: 'PASSIVER', type: 'EQUITY', isHeader: true },
  { number: 6501, name: 'Egenkapital', type: 'EQUITY', isHeader: true },
  { number: 6502, name: 'Virksomhedskapital', type: 'EQUITY', isHeader: false },
  { number: 6510, name: 'Registreret kapital mv.', type: 'EQUITY', isHeader: false, parentGroup: 6502 },
  { number: 6520, name: 'Indbetalt registreret kapital mv.', type: 'EQUITY', isHeader: false, parentGroup: 6502 },
  { number: 6525, name: 'Ikke indbetalt registreret kapital mv.', type: 'EQUITY', isHeader: false, parentGroup: 6502 },
  { number: 6531, name: 'Overkurs ved emission', type: 'EQUITY', isHeader: false },
  { number: 6540, name: 'Overkurs ved emission', type: 'EQUITY', isHeader: false, parentGroup: 6531 },
  { number: 6551, name: 'Reserve for opskrivninger', type: 'EQUITY', isHeader: false },
  { number: 6560, name: 'Reserve for opskrivninger', type: 'EQUITY', isHeader: false, parentGroup: 6551 },
  { number: 6591, name: 'Andre reserver', type: 'EQUITY', isHeader: false },
  { number: 6800, name: 'Reserve for nettoopskrivning efter den indre værdis metode', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6810, name: 'Reserve for udlån og sikkerhedsstillelse', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6830, name: 'Reserve for ikke indbetalt virksomhedskapital og overkurs', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6840, name: 'Reserve for udviklingsomkostninger', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6870, name: 'Øvrige lovpligtige reserver', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6890, name: 'Vedtægtsmæssige reserver', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6910, name: 'Øvrige reserver', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6914, name: 'Reserve for iværksætterselskaber', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6915, name: 'Egenkapital primo (kun klasse A)', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6916, name: 'Årets resultat (kun klasse A)', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6917, name: 'Fri bil (kun klasse A)', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6918, name: 'Rejse og befordringsgodtgørelse (kun klasse A)', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6919, name: 'Fri telefon (Kun klasse A)', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6920, name: 'Private andele (Kun klasse A)', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6921, name: 'Private afskrivninger (Kun klasse A)', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6922, name: 'Driftsudgifter uden fradrag (Kun klasse A)', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6923, name: 'Privat hævet (kun klasse A)', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6924, name: 'Privat indskud (kun klasse A)', type: 'EQUITY', isHeader: false, parentGroup: 6591 },
  { number: 6931, name: 'Overført resultat', type: 'EQUITY', isHeader: false },
  { number: 6935, name: 'Overført resultat, primo', type: 'EQUITY', isHeader: false, parentGroup: 6931 },
  { number: 6940, name: 'Overført resultat, jf. resultatdisponering', type: 'EQUITY', isHeader: false, parentGroup: 6931 },
  { number: 6951, name: 'Foreslået udbytte indregnet under egenkapitalen', type: 'EQUITY', isHeader: false },
  { number: 6955, name: 'Foreslået udbytte, primo', type: 'EQUITY', isHeader: false, parentGroup: 6951 },
  { number: 6956, name: 'Udloddet udbytte', type: 'EQUITY', isHeader: false, parentGroup: 6951 },
  { number: 6960, name: 'Foreslået udbytte jf. resultatdisponeringen', type: 'EQUITY', isHeader: false, parentGroup: 6951 },
  { number: 6972, name: 'Hensatte forpligtelser', type: 'EQUITY', isHeader: true },
  { number: 6980, name: 'Hensættelser til pensioner og lignende forpligtelser', type: 'EQUITY', isHeader: false },
  { number: 6985, name: 'Hensættelser til pensioner og lignende forpligtelser', type: 'EQUITY', isHeader: false, parentGroup: 6980 },
  { number: 7000, name: 'Hensættelse til udskudt skat', type: 'LIABILITY', isHeader: false },
  { number: 7010, name: 'Hensættelser til udskudt skat', type: 'LIABILITY', isHeader: false, parentGroup: 7000 },
  { number: 7031, name: 'Andre hensatte forpligtelser', type: 'LIABILITY', isHeader: false },
  { number: 7040, name: 'Andre hensatte forpligtelser', type: 'LIABILITY', isHeader: false, parentGroup: 7031 },
  { number: 7052, name: 'Langfristede gældsforpligtelser', type: 'LIABILITY', isHeader: true },
  { number: 7053, name: 'Gæld, der er optaget ved udstedelse af obligationer (langfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7055, name: 'Gæld, der er optaget ved udstedelse af obligationer (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7053 },
  { number: 7061, name: 'Konvertible og udbyttegivende gældsbreve (langfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7065, name: 'Konvertible og udbyttegivende gældsbreve (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7061 },
  { number: 7080, name: 'Gæld til kreditinstitutter (langfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7110, name: 'Gæld til kredit- og realkreditinstitutter (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7080 },
  { number: 7120, name: 'Gæld til banker (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7080 },
  { number: 7125, name: 'Leasingforpligtelser (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7080 },
  { number: 7126, name: 'Øvrig langfristet gæld', type: 'LIABILITY', isHeader: false, parentGroup: 7080 },
  { number: 7141, name: 'Modtagne forudbetalinger fra kunder (langfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7145, name: 'Modtagne forudbetalinger fra kunder (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7141 },
  { number: 7151, name: 'Leverandører af varer og tjenesteydelser (langfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7155, name: 'Leverandører af varer og tjenesteydelser (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7151 },
  { number: 7161, name: 'Vekselgæld (langfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7165, name: 'Vekselgæld (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7161 },
  { number: 7171, name: 'Gæld til tilknyttede virksomheder (langfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7175, name: 'Gæld til tilknyttede virksomheder (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7171 },
  { number: 7181, name: 'Gæld til kapitalinteresser (langfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7185, name: 'Gæld til kapitalinteresser (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7181 },
  { number: 7191, name: 'Anden gæld, herunder skyldige skatter og skyldige bidrag til social sikring (langfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7195, name: 'Anden gæld (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7191 },
  { number: 7210, name: 'Gæld til virksomhedssdeltagere og ledelse (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7191 },
  { number: 7230, name: 'Deposita (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7191 },
  { number: 7240, name: 'Leasingforpligtelse (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7191 },
  { number: 7250, name: 'Skyldig selskabsskat (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7191 },
  { number: 7261, name: 'Periodeafgrænsningsposter (langfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7265, name: 'Periodeafgrænsningsposter (langfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7261 },
  { number: 7280, name: 'Kortfristede gældsforpligtelser', type: 'LIABILITY', isHeader: true },
  { number: 7281, name: 'Gæld, der er optaget ved udstedelse af obligationer (kortfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7285, name: 'Gæld, der er optaget ved udstedelse af obligationer (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7281 },
  { number: 7291, name: 'Konvertible og udbyttegivende gældsbreve (kortfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7295, name: 'Konvertible og udbyttegivende gældsbreve (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7291 },
  { number: 7301, name: 'Gæld til kreditinstitutter (kortfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7310, name: 'Gæld til kredit- og realkreditinstitutter (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7301 },
  { number: 7330, name: 'Gæld til banker (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7301 },
  { number: 7345, name: 'Leasingforpligtelser (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7301 },
  { number: 7350, name: 'Øvrig kortfristet gæld', type: 'LIABILITY', isHeader: false, parentGroup: 7301 },
  { number: 7401, name: 'Modtagne forudbetalinger fra kunder (kortfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7410, name: 'Modtagne forudbetalinger fra kunder (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7401 },
  { number: 7421, name: 'Leverandører af varer og tjenesteydelser (kortfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7440, name: 'Leverandører af varer og tjenesteydelser (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7421 },
  { number: 7451, name: 'Igangværende arbejder for fremmed regning (kortfristet gæld)', type: 'LIABILITY', isHeader: false },
  { number: 7455, name: 'Igangværende arbejder for fremmed regning (kortfristet gæld)', type: 'LIABILITY', isHeader: false, parentGroup: 7451 },
  { number: 7456, name: 'Modtagne acontobetalinger (kortfristet gæld)', type: 'LIABILITY', isHeader: false, parentGroup: 7451 },
  { number: 7461, name: 'Vekselgæld (kortfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7465, name: 'Vekselgæld (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7461 },
  { number: 7501, name: 'Gæld til tilknyttede virksomheder (kortfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7510, name: 'Gæld til tilknyttede virksomheder (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7501 },
  { number: 7531, name: 'Gæld til kapitalinteresser (kortfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7535, name: 'Gæld til kapitalinteresser (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7531 },
  { number: 7581, name: 'Anden gæld, herunder skyldige skatter og skyldige bidrag til social sikring (kortfristet)', type: 'LIABILITY', isHeader: false },
  { number: 7590, name: 'Gæld til virksomhedsdeltagere og ledelse (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7610, name: 'Deposita (kortfristet)', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7680, name: 'Salgsmoms', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7700, name: 'Moms af varekøb udland, EU og ikke-EU', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7720, name: 'Moms af ydelseskøb udland, EU og ikke-EU', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7740, name: 'Købsmoms', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7760, name: 'Olie- og flaskegasafgift', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7780, name: 'Elafgift', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7800, name: 'Naturgas- og bygasafgift', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7810, name: 'Kulafgift', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7820, name: 'Vandafgift', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7830, name: 'Co2-afgift', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7840, name: 'Skyldig moms', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7860, name: 'Skyldig løn og gager', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7880, name: 'Skyldig bonus og tantieme', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7900, name: 'Skyldige feriepenge', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7920, name: 'Skyldig A-skat', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7940, name: 'Skyldigt AM-bidrag', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7960, name: 'Skyldigt ATP-bidrag', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 7980, name: 'Skyldigt AMP-bidrag', type: 'LIABILITY', isHeader: false, parentGroup: 7581 },
  { number: 8000, name: 'Anden skyldig pension', type: 'YEAR_END', isHeader: false, parentGroup: 7581 },
  { number: 8010, name: 'Skyldig arbejdsgiverbidrag (samlet betaling)', type: 'YEAR_END', isHeader: false, parentGroup: 7581 },
  { number: 8030, name: 'Skyldig feriepengeforpligtigelse', type: 'YEAR_END', isHeader: false, parentGroup: 7581 },
  { number: 8035, name: 'Skyldigt ferietillæg', type: 'YEAR_END', isHeader: false, parentGroup: 7581 },
  { number: 8040, name: 'Øvrig anden gæld', type: 'YEAR_END', isHeader: false, parentGroup: 7581 },
  { number: 8045, name: 'Modtagne offentlige tilskud til senere beskatning', type: 'YEAR_END', isHeader: false, parentGroup: 7581 },
  { number: 8051, name: 'Periodeafgrænsningsposter (kortfristet)', type: 'YEAR_END', isHeader: false },
  { number: 8070, name: 'Periodeafgrænsningsposter (kortfristet)', type: 'YEAR_END', isHeader: false, parentGroup: 8051 },
];

/**
 * Officiel Standardkontoplan (version 20260101) — 603 konti.
 * Eksporteret i det format som StandardAccount-interfacet forventer.
 * Brug denne i stedet for det gamle manuelle PUBLIC_STANDARD_CHART-array.
 */
export const OFFICIAL_STANDARD_CHART: StandardAccount[] = ALL_ACCOUNTS.map((a) => ({
  number: a.number.toString(),
  name: a.name,
  nameEn: a.name, // Officiel JSON har kun danske navne
  type: a.type,
  description: a.isHeader ? `Hovedkonto: ${a.name}` : (a.parentGroup ? `Underkonto til ${a.parentGroup}: ${a.name}` : a.name),
  suggestedFSR: FSR_SUGGESTIONS[a.number],
}));

/** Summeret antal konti i den officielle standardkontoplan. */
export const OFFICIAL_CHART_COUNT = OFFICIAL_STANDARD_CHART.length;