/**
 * SAF-T Financial DK v2.1 — Officielle Momskoder
 *
 * Kilde: Erhvervsstyrelsen, Standardkontoplanen/JSON/2026-01-01-Momskoder-Bruttoliste.json
 * Version: 2026-01-01 (gyldig fra 2026-01-01)
 * Repo: https://git.erst.dk/standard-filformater/standard-filformater
 *
 * Denne fil indeholder alle 72 officielle momskoder fra Momskoder-Bruttoliste
 * (Excel-ark: 2026-01-01 Standardkontoplan.xlsx, sheet III) Momskoder Bruttoliste).
 *
 * Hver kode indeholder:
 *   - standardCode:  Officiel standardkode (f.eks. "S01", "K010") — bruges i SAF-T <StandardTaxCode>
 *   - legacyCode:    Ældre officiel kode (f.eks. "S1", "K1") — bagudkompatibilitet
 *   - codeRef:       Momskode betegnelse (f.eks. "S-DK-25", "K-DK-Fradrag")
 *   - alphaFlowCode: AlphaFlow intern kode der mapper til denne (f.eks. "S25", "K25") — null = ikke mappet
 *   - rate:          Momssats som heltal (0, 12, 25) — 0 = ikke anvendelig / variabel
 *   - group:         Gruppebetegnelse (f.eks. "Salg", "Køb fra EU-lande")
 *   - heading:       Overskrift / kort beskrivelse fra Excel
 *   - deductible:    Fradragsret ("1" = fuldt, "0" = ingen, "Delvis", "Skøn", etc.)
 *   - reportingRule: Angivelsesregel (f.eks. "Salgsmoms (udgående moms)", "Rubrik C")
 *   - guidance:      Vejledning fra Excel (forklarende tekst om hvornår koden anvendes)
 *
 * SAF-T XSD v2.1 kræver at hver <TaxCodeDetails> har:
 *   <TaxCode>          = system-specifik kode (AlphaFlow's interne kode)
 *   <StandardTaxCode>  = officiel kode fra Momskoder-Bruttoliste (f.eks. "S01")
 *   <Description>      = menneskelæsbar beskrivelse
 *   <TaxPercentage>    = momssats som decimal
 *   <Country>          = "DK"
 */

export interface SaftVatCode {
  /** Officiel standardkode (f.eks. "S01", "K030") — bruges i <StandardTaxCode> */
  standardCode: string;
  /** Ældre officiel kode (f.eks. "S1", "K30") — bagudkompatibilitet */
  legacyCode: string;
  /** Momskode betegnelse fra Excel (f.eks. "S-DK-25", "K-DK-Fradrag") */
  codeRef: string;
  /** AlphaFlow intern kode der mapper til denne officielle kode */
  alphaFlowCode: string | null;
  /** Momssats som heltal (0, 12, 25) — 0 = ikke anvendelig / variabel */
  rate: number;
  /** Gruppebetegnelse (f.eks. "Salg", "Køb fra EU-lande") */
  group: string;
  /** Overskrift / kort beskrivelse fra Excel */
  heading: string;
  /** Fradragsret ("1" = fuldt, "0" = ingen, "Delvis", "Skøn", etc.) */
  deductible: string;
  /** Angivelsesregel (f.eks. "Salgsmoms (udgående moms)", "Rubrik C") */
  reportingRule: string;
  /** Vejledning fra Excel — forklarende tekst om hvornår koden anvendes */
  guidance: string;
}

/**
 * De 72 officielle momskoder fra Momskoder-Bruttoliste (2026-01-01).
 *
 * Kilde: Excel-ark "2026-01-01 Standardkontoplan.xlsx", sheet III) Momskoder Bruttoliste
 * — automatisk udtrukket fra kolonnerne: Momskode betegnelse (D), Momskode NY (F),
 * Momskode (G), Momskode NY (H), Momsangivelse (I), Vejledning (J).
 *
 * Kun de koder der er relevante for AlphaFlow's nuværende interne koder
 * har en alphaFlowCode mapping. De resterende er medtaget for fuldstændighed
 * og kan bruges når nye transaktionstyper tilføjes.
 */
export const SAFT_VAT_CODES: SaftVatCode[] = [
{ standardCode: 'S01', legacyCode: 'S1', codeRef: 'S-DK-25', alphaFlowCode: 'S25', rate: 25, group: 'Salg', heading: 'Momspligtige salg (DK), 25% moms', deductible: '', reportingRule: 'Salgsmoms (udgående moms)', guidance: 'Denne kode anvendes til håndtering af transaktioner med 25% salgsmoms, eksempelvis salg af momspligtige varer eller ydelser i DK.' },
{ standardCode: 'S02', legacyCode: 'S0', codeRef: 'S-DK-0', alphaFlowCode: 'S0', rate: 0, group: 'Salg', heading: 'Momspligtige salg (DK) 0% moms', deductible: '', reportingRule: 'Skal som udgangspunkt medtages i rubrik C, hvis feks. indenlandsk omvendt betalingspligt, salg til skibe i udenrigsfart, salg af aviser', guidance: 'Denne kode anvendes til håndtering af transaktioner i DK der er momspligtige, men hvor der ikke skal afregnes moms. Det kan eksempelvis være salg med indenlandsk omvendt betalingspligt, salg til skibe' },
{ standardCode: 'S81', legacyCode: 'S%', codeRef: 'S-DK-U', alphaFlowCode: null, rate: 0, group: 'Salg', heading: 'Udenfor momslovens anvendelsområde', deductible: '', reportingRule: 'Skal ikke medtages i angivelsen', guidance: 'Denne kode anvendes til ”omsætning”, der ikke er omfattet af momsloven. Det kan eksempelvis være modtagne sponsorater uden modydelse mv.' },
{ standardCode: 'S82', legacyCode: 'SMF', codeRef: 'S-DK-MF', alphaFlowCode: null, rate: 0, group: 'Salg', heading: 'Momsfritaget salg', deductible: '', reportingRule: 'Skal ikke medtages i angivelsen', guidance: 'Denne kode anvendes til salg af varer og ydelser, der er omfattet af momslovens fritagelsesbestemmelser, eksempelvis momsfritaget undervisning, hospitalsbehandling, foreningskontingenter.' },
{ standardCode: 'S83', legacyCode: 'Sbrugt', codeRef: 'S-DK-Brugtmoms', alphaFlowCode: null, rate: 25, group: 'Salg', heading: 'Brugtmoms', deductible: '', reportingRule: 'Salgsmoms (udgående moms)', guidance: 'Denne kode anvendes ved salg af varer der kan omfattes af reglerne for beregning af moms af brugte varer og hvor der derfor skal afregnes moms af forskellen mellem salgsprisen og købsprisen.' },
{ standardCode: 'S84', legacyCode: 'Smargin', codeRef: 'S-DK-Marginmoms', alphaFlowCode: null, rate: 25, group: 'Salg', heading: 'Marginmoms', deductible: '', reportingRule: 'Salgsmoms (udgående moms)', guidance: 'Denne kode anvendes af rejsebureauer mv., der skal afregne moms af fortjenstmargen.' },
{ standardCode: 'S85', legacyCode: 'Smotor', codeRef: 'S-DK-brugtbil', alphaFlowCode: null, rate: 25, group: 'Salg', heading: 'Brugte personmotorkøretøjer', deductible: '', reportingRule: 'Salgsmoms (udgående moms)', guidance: 'Denne kode anvendes ved salg af brugte personbiler, hvor sælger kan foretage et fradrag i den beregnede salgsmoms, på baggrund af beregning baseret på købsprisen på det brugte køretøj.' },
{ standardCode: 'S86', legacyCode: 'Sleasing', codeRef: 'S-DK-leasingbiler-mm', alphaFlowCode: null, rate: 20, group: 'Salg', heading: 'Udlejningsvirksomheder, køreskoler og demobiler', deductible: '', reportingRule: 'Salgsmoms (udgående moms)', guidance: 'Denne kode anvendes ved en virksomheds salg af udlejnings-, køreskole- og demokøretøjer, hvor der beregnes moms efter de konkrete forhold på salgstidspunktet.  Moms ved salg af leasingbiler udgør 20% ' },
{ standardCode: 'S87', legacyCode: 'Skunstnere', codeRef: 'S-DK-kunstnere', alphaFlowCode: null, rate: 5, group: 'Salg', heading: 'Kunstneres førstegangssalg', deductible: '', reportingRule: 'Salgsmoms (udgående moms)', guidance: 'Denne kode anvendes ved kunstneres førstegangssalg af egne værker, når disse opfylder momslovens betingelser for at blive anset som kunstgenstande.' },
{ standardCode: 'S88', legacyCode: 'Slokal', codeRef: 'S-LokalMoms', alphaFlowCode: null, rate: 0, group: 'Salg', heading: 'Lokal salg andre lande med moms', deductible: '', reportingRule: 'Skal ikke medtages i angivelsen', guidance: 'Denne kode anvendes ved salg foretaget i eller til kunder i andre lande, hvor salget gennemføres med lokal moms.' },
{ standardCode: 'S21', legacyCode: 'S2', codeRef: 'S-EU-V-0', alphaFlowCode: 'SEU', rate: 0, group: 'Salg til EU-lande', heading: 'Varesalg B2B (EU), 0% moms', deductible: '', reportingRule: 'Rubrik B - varer', guidance: 'Denne kode anvendes ved salg af varer til momsregistrerede kunder i andre EU-lande.' },
{ standardCode: 'S22', legacyCode: 'S7', codeRef: 'S-EU-V-0%', alphaFlowCode: null, rate: 0, group: 'Salg til EU-lande', heading: 'Varesalg B2B (EU), 0% moms, ingen EU-salgsangivelse', deductible: '', reportingRule: 'Rubrik B – oplysninger, der ikke skal indberettes til ”EU-salg uden moms”', guidance: 'Denne kode anvendes ved salg af nye transportmidler til ikke registrerede virksomheder og private forbrugere. Installering og montering af varer, samt fjernsalg af varer til andre EU-lande' },
{ standardCode: 'S23', legacyCode: 'S3', codeRef: 'S-EU-Y-0', alphaFlowCode: null, rate: 0, group: 'Salg til EU-lande', heading: 'Ydelsessalg B2B (EU), 0% moms', deductible: '', reportingRule: 'Rubrik B - ydelser', guidance: 'Denne kode anvendes ved salg af ydelser til kunder i andre EU-lande, hvor kunden skal afregne moms i eget land.' },
{ standardCode: 'S24', legacyCode: 'SMFEU', codeRef: 'S-EU-MF', alphaFlowCode: null, rate: 0, group: 'Salg til EU-lande', heading: 'Momsfritaget salg (EU)', deductible: '', reportingRule: 'Skal ikke medtages i angivelsen', guidance: 'Denne kode anvendes til salg af varer og ydelser til andre EU lande, der er omfattet af momslovens fritagelsesbestemmelser, eksempelvis momsfritaget undervisning, hospitalsbehandling, foreningskonting' },
{ standardCode: 'S25', legacyCode: 'S8', codeRef: 'S-EU-V-TR', alphaFlowCode: null, rate: 0, group: 'Salg til EU-lande', heading: 'Varesalg B2B (EU). Trekantshandel', deductible: '', reportingRule: 'Skal ikke medtages på momsangivelsen, men som trekantshandel på EU-salgsangivelsen', guidance: 'Denne kode anvendes ved køb af varer fra et EU-land og sendes fra sælger land til en kunde i et andet EU-land (ikke DK), som afregner momsen i eget land.' },
{ standardCode: 'S41', legacyCode: 'S4', codeRef: 'S-%EU-V-0', alphaFlowCode: null, rate: 0, group: 'Salg til lande udenfor EU', heading: 'Varesalg B2B (% EU), 0% moms', deductible: '', reportingRule: 'Rubrik C - eksport udenfor EU', guidance: 'Denne kode anvendes ved salg af varer til kunder i lande udenfor EU og hvor varen eksporteres ud af EU.' },
{ standardCode: 'S42', legacyCode: 'S5', codeRef: 'S-%EU-Y-0', alphaFlowCode: null, rate: 0, group: 'Salg til lande udenfor EU', heading: 'Ydelsessalg B2B (% EU), 0% moms', deductible: '', reportingRule: 'Rubrik C - eksport udenfor EU', guidance: 'Denne kode anvendes ved salg af ydelser til kunder i lande udenfor EU.' },
{ standardCode: 'S43', legacyCode: 'S6', codeRef: 'S-%EU-MF', alphaFlowCode: null, rate: 0, group: 'Salg til lande udenfor EU', heading: 'Momsfritaget salg (udenfor EU) § 13', deductible: '', reportingRule: 'Skal ikke medtages i angivelsen', guidance: 'Denne kode anvendes til salg af varer og ydelser til kunder i lande udenfor EU, når varen eller ydelsen er omfattet af momslovens fritagelsesbestemmelser, eksempelvis momsfritaget undervisning, hospit' },
{ standardCode: 'S61', legacyCode: 'S-OSS-Y', codeRef: 'S-OSS-Y', alphaFlowCode: null, rate: 0, group: 'OSS - One stop shop salg (onlinehandel)', heading: 'B2C Ydelsessalg omfattet af OSS', deductible: '', reportingRule: 'OSS angivelsen + momsangivelsens rubrik C', guidance: 'Denne kode anvendes ved salg af ydelser til kunder i andre EU-lande med lokal moms (f.eks. privatpersoner), når salget er omfattet af reglerne for One Stop Shop. F.eks. Salg af ydelser fra en leverand' },
{ standardCode: 'S62', legacyCode: 'S-OSS-V-DK-EU', codeRef: 'S-OSS-V-F S-OSS-V-DK-EU', alphaFlowCode: null, rate: 0, group: 'OSS - One stop shop salg (onlinehandel)', heading: 'B2C varesalg fra DK til andre EU-lande', deductible: '', reportingRule: 'OSS angivelsen + Rubrik B - oplysninger der ikke skal indberettes til "EU-salg uden moms"', guidance: 'Denne kode anvendes ved salg af varer til kunder i andre EU-lande med lokal moms (f.eks. privatpersoner, hvor varen forsendes fra DK), når salget er omfattet af reglerne for One Stop Shop.' },
{ standardCode: 'S63', legacyCode: 'S-OSS-V-%DK', codeRef: 'S-OSS-V-%DK', alphaFlowCode: null, rate: 0, group: 'OSS - One stop shop salg (onlinehandel)', heading: 'B2C varesalg fra andre EU-lande eller lande udenfor EU', deductible: '', reportingRule: 'OSS angivelsen + Rubrik C', guidance: 'Denne kode anvendes ved salg af varer til kunder i andre EU-lande med lokal moms (f.eks. privatpersoner, hvor varen forsendes fra et andet EU-land end det hvor varen modtages, når leverandøren er tilk' },
{ standardCode: 'S64', legacyCode: 'S-OSS-V-%EU-DK', codeRef: 'S-OSS-V-%EU-DK', alphaFlowCode: null, rate: 25, group: 'OSS - One stop shop salg (onlinehandel)', heading: 'B2C varesalg fra et land udenfor EU til kunde i DK', deductible: '', reportingRule: 'OSS angivelsen (skal ikke angives på momsangivelsen)', guidance: 'Denne kode anvendes ved salg af varer til kunder i Danmark med lokal moms (f.eks. privatpersoner, hvor varen forsendes fra et land uden for EU og leverandøren er tilknyttet importordningen ), når salg' },
{ standardCode: 'S65', legacyCode: 'S-OSS-V-L', codeRef: 'S-OSS-V-L', alphaFlowCode: null, rate: 25, group: 'OSS - One stop shop salg (onlinehandel)', heading: 'B2C varesalg (lokalt salg)', deductible: '', reportingRule: 'OSS angivelsen + rubrik A  - varer', guidance: 'Denne kode anvendes ved salg af varer til kunder i Danmark med lokal moms (f.eks. privatpersoner i Danmark, hvor varen befinder sig i et andet EU-land på salgstidspunktet), når salget er omfattet af r' },
{ standardCode: 'K010', legacyCode: 'K1', codeRef: 'K-DK-Fradrag', alphaFlowCode: 'K25', rate: 25, group: 'Køb', heading: 'Indgående moms (DK), fuld fradrag (100%)', deductible: '1', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb af varer eller ydelser med moms i DK, hvor varen eller ydelsen anvendes fuldt ud i forbindelse med virksomhedens momspligtige aktiviteter og hvor varen eller ydelsen ikke e' },
{ standardCode: 'K020', legacyCode: 'K3', codeRef: 'K-DK-SkønsmæssigFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Indgående moms (DK), skønsmæssigt fradrag', deductible: 'Skøn', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb af varer eller ydelser, der både anvendes i forbindelse med de momspligtige aktiviteter og til formål der er virksomheden uvedkommende og hvor retten til fradrag skal opgør' },
{ standardCode: 'K030', legacyCode: 'K0', codeRef: 'K-DK-IngenFradrag', alphaFlowCode: 'K0', rate: 0, group: 'Køb', heading: 'Momsfritaget køb, Ingen fradrag, ingen moms på køb', deductible: '', reportingRule: 'Skal ikke medtages i angivelsen', guidance: 'Denne kode anvendes ved køb af varer eller ydelser, hvor virksomheden ikke har adgang til momsfradrag eller køb af varer og ydelser uden moms, når varen eller ydelsen er omfattet af momslovens fritage' },
{ standardCode: 'K610', legacyCode: 'K7', codeRef: 'K-DK-VejFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Indgående moms (DK), lovbestemt delvist fradrag (2/3 fradrag)', deductible: '66,6%', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved vedligeholdelse af tilkørselsveje i landbrugsvirksomheder, hvor 2/3 af momsen på udgiften kan fradrages.' },
{ standardCode: 'K040', legacyCode: 'K5A', codeRef: 'K-DK-FastnettelefonFuld', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Indgående moms (DK), lovbestemt delvist fradrag (50%)', deductible: '0.5', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb og drift af fastnettelefoner på medarbejderes privatadresse, når virksomheden alene har momspligtige aktiviteter.' },
{ standardCode: 'K050', legacyCode: 'K5B', codeRef: 'K-DK-FastnettelefonProRata', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Indgående moms (DK), lovbestemt delvist fradrag (50% x pro rata)', deductible: '0.5', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb og drift af fastnettelefoner på medarbejderes privatadresse, når virksomheden har både momsfrie og momspligtige aktiviteter.' },
{ standardCode: 'K060', legacyCode: 'KL1', codeRef: 'K-DK-GulpladebilFradragPrivat', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Leasing og drift af gulpladebil, (private og blandede formål samt erhverv)', deductible: '0.333', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved leje af varebiler (med tilladt totalvægt på ikke over 3t), når disse ikke udelukkende anvendes i virksomheden.' },
{ standardCode: 'K070', legacyCode: 'K25A', codeRef: 'K-DK-RepræsentationFradragFuld', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Repræsentationsmoms, delvist fradragsberettiget (25%)', deductible: '0.25', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb af repræsentationsydelser, f.eks. restaurationsydelser, hvor ¼ af momsen på udgiften kan fradrages.' },
{ standardCode: 'K080', legacyCode: 'K25B', codeRef: 'K-DK-RepræsentationFradragProRata', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Repræsentationsmoms, delvist fradragsberettiget (25% x pro rata)', deductible: '0.25', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb af repræsentationsydelser, f.eks. restaurationsydelser, i virksomheder med både momsfri og momspligtige aktiviteter, hvor ¼ * pro rata satsen af momsen på udgiften kan frad' },
{ standardCode: 'K090', legacyCode: 'KL2', codeRef: 'K-DK-LeasinghvidpladebilFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Leasing af hvidpladebil i min. 6 mdr.  (faktura)', deductible: 'Maks 25% af særligt fradrags-grundlag', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved leasing af hvidpladebiler i perioder længere end 6 mdr., hvor bilen anvendes min. 10 pct. i forbindelse med virksomhedens momspligtige aktiviteter. Den moms, der kan fradrages,' },
{ standardCode: 'K100', legacyCode: 'KL3', codeRef: 'K-DK-LeasinghvidpladebilFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Leasing af hvidpladebil i min. 6 mdr.  (faktura x pro rata)', deductible: 'Maks 25% af særligt fradrags-grundlag', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved virksomheder med både momsfri og momspligtige aktiviteters leasing af hvidpladebiler i perioder længere ind 6 mdr, hvor bilen anvendes min. 10 pct. i forbindelse med virksomhe' },
{ standardCode: 'K110', legacyCode: 'K2', codeRef: 'K-DK-DelvisFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Indgående moms (DK), Delvis fradrag (pro rata)', deductible: 'Delvis', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes af virksomheder med både momsfri og momspligtige aktiviteters afholdelse af fællesomkostninger, dvs. omkostninger der både vedrører virksomhedens momspligtige og momsfrie aktivitet' },
{ standardCode: 'K120', legacyCode: 'K6', codeRef: 'K-DK-SektorFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Indgående moms (DK), sektorbaseret fradragsret', deductible: 'Sektor', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb i virksomheder, der har en sektorisk opdeling og dermed skal opgøre et særligt momsfradrag for denne del af virksomheden.' },
{ standardCode: 'K130', legacyCode: 'K4', codeRef: 'K-DK-ArealFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Arealbaseret fradragsret fast ejendom', deductible: 'Arealfordeling', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved afholdelse af udgifter til opførelse, ombygning, reparation og vedligeholdelse af bygninger, når bygningen også omfatter lokaler, der vedrører andre formål end virksomhedens mo' },
{ standardCode: 'K620', legacyCode: 'K-brugtmoms', codeRef: 'K-DK-Brugtmoms', alphaFlowCode: null, rate: 0, group: 'Køb', heading: 'Brugtmoms', deductible: '', reportingRule: 'Angives ikke direkte på momsangivelsen - indgår i særligt beregningsgrundlag', guidance: 'Denne kode anvendes ved køb af varer under brugtmomsordningen. Købssummen skal alene anvendes til at opgøre beregningsgrundlaget for salgsmoms og udløser ikke adgang til momsfradrag.' },
{ standardCode: 'K630', legacyCode: 'K-marginmoms', codeRef: 'K-DK-Marginmoms', alphaFlowCode: null, rate: 0, group: 'Køb', heading: 'Marginmoms', deductible: '', reportingRule: 'Angives ikke direkte på momsangivelsen - indgår i særligt beregningsgrundlag', guidance: 'Denne kode anvendes ved køb af varer under marginmomsordningen. Købssummen skal alene anvendes til at opgøre beregningsgrundlaget for salgsmoms og udløser ikke adgang til momsfradrag.' },
{ standardCode: 'K640', legacyCode: 'K-brugtbil', codeRef: 'K-DK-brugtbil', alphaFlowCode: null, rate: 0, group: 'Køb', heading: 'Brugte personmotorkøretøjer', deductible: '', reportingRule: 'Angives ikke direkte på momsangivelsen - indgår i særligt beregningsgrundlag', guidance: 'Denne kode anvendes ved køb af brugte personbiler til videresalg. Købssummen skal alene anvendes til at opgøre beregningsgrundlaget for salgsmoms og udløser ikke adgang til momsfradrag.' },
{ standardCode: 'K650', legacyCode: 'K-leasingbil', codeRef: 'K-DK-leasingbiler-mm', alphaFlowCode: null, rate: 0, group: 'Køb', heading: 'Udlejningsvirksomheder, køreskoler og demobiler', deductible: '', reportingRule: 'Angives ikke direkte på momsangivelsen - indgår i særligt beregningsgrundlag', guidance: 'Denne kode anvendes ved køb af udlejnings-, køreskole- eller demobiler, når der vælges at beregne salgsmoms efter den særlige metode i momslovens §30, stk. 1' },
{ standardCode: 'K660', legacyCode: 'K-DK0-1', codeRef: 'K-DKO-Fradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'DK omvendt betalingspligt, Indgående moms, fuldt fradragsberettiget (100%)', deductible: '1', reportingRule: 'Salgsmoms (udgående) og købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb af varer i DK der er omfattet af lokal omvendt betalingspligt, f.eks. mobiltelefoner, bærbare pc, tablets, metalskrot, co2-kvoter mv.' },
{ standardCode: 'K670', legacyCode: 'K-DKO-2', codeRef: 'K-DKO-DelvisFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'DK omvendt betalingspligt, Indgående moms, Delvis fradrag (pro rata)', deductible: 'Delvis', reportingRule: 'Salgsmoms og købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb af varer i DK der er omfattet af lokal omvendt betalingspligt, f.eks. mobiltelefoner, bærbare pc, tablets, metalskrot, co2-kvoter mv., når købet vedrører både virksomhedens' },
{ standardCode: 'K680', legacyCode: 'K-DKO-3', codeRef: 'K-DKO-SkønsmæssigFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'DK omvendt betalingspligt, Indgående moms, skønsmæssigt fradrag', deductible: 'Skøn', reportingRule: 'Salgsmoms og købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb af varer i DK der er omfattet af lokal omvendt betalingspligt, f.eks. mobiltelefoner, bærbare pc, tablets, metalskrot, co2-kvoter mv., når købet vedrører både virksomhedens' },
{ standardCode: 'K690', legacyCode: 'K-DKO-0', codeRef: 'K-DKO-IngenFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'DK omvendt betalingspligt, Ingen fradrag', deductible: '', reportingRule: 'Salgsmoms (udgående moms)', guidance: 'Denne kode anvendes ved køb af varer i DK der er omfattet af lokal omvendt betalingspligt, f.eks. mobiltelefoner, bærbare pc, tablets, metalskrot, co2-kvoter mv., når købet vedrører enten virksomheden' },
{ standardCode: 'K700', legacyCode: 'K-DKO-4', codeRef: 'K-DKO-ArealFradrag', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'DK omvendt betalingspligt, Arealbaseret fradragsret fast ejendom', deductible: 'Arealfordeling', reportingRule: 'Salgsmoms og købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb af varer i DK der er omfattet af lokal omvendt betalingspligt, f.eks. mobiltelefoner, bærbare pc, tablets, metalskrot, co2-kvoter mv., når købet vedrører opførelse, ombygni' },
{ standardCode: 'K710', legacyCode: 'K-LokalMoms', codeRef: 'K-LokalMoms', alphaFlowCode: null, rate: 0, group: 'Køb', heading: 'Køb med lokal moms', deductible: 'Refusion', reportingRule: 'Tilbagesøgning efter refusionsordningsreglerne', guidance: 'Denne kode anvendes ved køb af varer og ydelser i andre lande, hvor virksomheden har modtaget en faktura eller en kvittering med lokal moms, f.eks. Rejseudgifter' },
{ standardCode: 'K720', legacyCode: 'K-DKO-I', codeRef: 'K-DK-refusion', alphaFlowCode: null, rate: 25, group: 'Køb', heading: 'Køb omfattet af det offentliges refusionsordning', deductible: 'Refusion', reportingRule: 'Angives ikke på momsangivelsen - indgår i opgørelsen ved refusionsordning', guidance: 'Denne kode anvendes ved køb hvor virksomheden har mulighed for kompensation eller refusion for den konkrete udgift.' },
{ standardCode: 'K210', legacyCode: 'K-EU-V-1', codeRef: 'K-EU-V-Fradrag', alphaFlowCode: 'KEU', rate: 25, group: 'Køb fra EU-lande', heading: 'Varekøb, erhvervelsesmoms (EU), fuldt fradragsberettiget (100%)', deductible: '1', reportingRule: 'Rubrik A - varer + Moms af varekøb i udlandet (både EU og lande uden for EU) og Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved varekøb uden moms i andre EU-lande, hvor virksomheden har fuldt fradrag for den beregnede erhvervelsesmoms.' },
{ standardCode: 'K220', legacyCode: 'K-EU-V-3', codeRef: 'K-EU-V-SkønsmæssigFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Varekøb, erhvervelsesmoms (EU), skønsmæssigt fradrag', deductible: 'Skøn', reportingRule: 'Rubrik A - varer + Moms af varekøb i udlandet (både EU og lande uden for EU) og Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved varekøb uden moms i andre EU-lande, hvor den indkøbte vare både anvendes i forbindelse med de momspligtige aktiviteter og til formål der er virksomheden uvedkommende og hvor r' },
{ standardCode: 'K230', legacyCode: 'K-EU-V-0', codeRef: 'K-EU-V-IngenFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Varekøb, erhvervelsesmoms (EU), ingen fradrag', deductible: '', reportingRule: 'Rubrik A - varer + Moms af varekøb i udlandet (både EU og lande uden for EU)', guidance: 'Denne kode  anvendes ved varekøb uden moms i andre EU-lande, hvor virksomheden ikke har adgang til fradrag for den beregnede moms, f.eks. fordi de indkøbte varer ikke anvendes i forbindelse med virkso' },
{ standardCode: 'K240', legacyCode: 'K-EU-V-2', codeRef: 'K-EU-V-DelvisFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Varekøb, erhvervelsesmoms (EU), Delvis fradrag (pro rata)', deductible: 'Delvis', reportingRule: 'Rubrik A - varer + Moms af varekøb i udlandet (både EU og lande uden for EU) og Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved varekøb uden moms i andre EU-lande, hvor den indkøbte vare både anvendes i forbindelse med de momspligtige og de momsfrie aktiviteter og hvor retten til fradrag for den beregn' },
{ standardCode: 'K250', legacyCode: 'K-EU-V-4', codeRef: 'K-EU-V-ArealFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Varekøb, erhvervelsesmoms (EU), Arealbaseret fradragsret fast ejendom', deductible: 'Arealfordeling', reportingRule: 'Rubrik A - varer + Moms af varekøb i udlandet (både EU og lande uden for EU)  samt Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved varekøb uden moms i andre EU-lande når købet vedrører opførelse, ombygning, reparation og vedligeholdelse af bygninger, når bygningen også omfatter lokaler der vedrører andre ' },
{ standardCode: 'K260', legacyCode: 'K-EU-Y-1', codeRef: 'K-EU-Y-Fradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Ydelseskøb, omvendt betalingspligt (EU), fuldt fradragsberettiget (100%)', deductible: '1', reportingRule: 'Rubrik A - ydelser + Moms af ydelseskøb i udlandet med omvendt betalingspligt og Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved ydelseskøb uden moms i andre EU-lande, hvor virksomheden har fuldt fradrag for den beregnede moms.' },
{ standardCode: 'K270', legacyCode: 'K-EU-Y-3', codeRef: 'K-EU-DK-Y-SkønsmæssigFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Ydelseskøb, omvendt betalingspligt (EU), skønsmæssigt fradrag', deductible: 'Skøn', reportingRule: 'Rubrik A - ydelser + Moms af ydelseskøb i udlandet med omvendt betalingspligt og Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved ydelseskøb uden moms i andre EU-lande, hvor den indkøbte ydelse både anvendes i forbindelse med de momspligtige aktiviteter og til formål der er virksomheden uvedkommende og h' },
{ standardCode: 'K280', legacyCode: 'K-EU-Y-0', codeRef: 'K-EU-Y-IngenFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Ydelseskøb, omvendt betalingspligt (EU), ingen fradrag', deductible: '', reportingRule: 'Rubrik A - ydelser + Moms af ydelseskøb i udlandet med omvendt betalingspligt', guidance: 'Denne kode  anvendes ved ydelseskøb uden moms i andre EU-lande, hvor virksomheden ikke har adgang til fradrag for den beregnede moms, f.eks. fordi de indkøbte ydelser ikke anvendes i forbindelse med v' },
{ standardCode: 'K290', legacyCode: 'K-EU-Y-2', codeRef: 'K-EU-Y-DelvisFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Ydelseskøb, omvendt betalingspligt (EU), Delvis fradrag', deductible: 'Delvis', reportingRule: 'Rubrik A - ydelser + Moms af ydelseskøb i udlandet med omvendt betalingspligt og Købsmoms (indgående moms - omsætningsfordeling)', guidance: 'Denne kode  anvendes ved ydelseskøb uden moms i andre EU-lande, hvor den indkøbte ydelse både anvendes i forbindelse med de momspligtige og de momsfrie aktiviteter og hvor retten til fradrag for den b' },
{ standardCode: 'K300', legacyCode: 'K-EU-Y-4', codeRef: 'K-EU-Y-ArealFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Ydelseskøb, omvendt betalingspligt (EU), Arealbaseret fradragsret fast ejendom', deductible: 'Arealfordeling', reportingRule: 'Rubrik A - ydelser + Moms af ydelseskøb i udlandet med omvendt betalingspligt og Købsmoms (indgående moms - forholdsmæssig andel)', guidance: 'Denne kode  anvendes ved ydelseskøb uden moms i andre EU-lande når købet vedrører opførelse, ombygning, reparation og vedligeholdelse af bygninger, når bygningen også omfatter lokaler der vedrører and' },
{ standardCode: 'K310', legacyCode: 'KL-EU-2', codeRef: 'K-EU-LeasinghvidpladebilFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Leasing af hvidpladebil i min. 6 mdr.  Udlandet (faktura)', deductible: 'Maks 25% af særligt fradrags-grundlag', reportingRule: 'Rubrik A - ydelser +  Moms af ydelseskøb i udlandet med omvendt betalingspligt og Købsmoms (indgående moms)', guidance: 'Denne kode anvendes af virksomheder med både momsfri og momspligtige aktiviteter ved leasing af hvidpladebiler i andre EU-lande i perioder længere ind 6 mdr, hvor bilen anvendes min. 10 pct. i forbind' },
{ standardCode: 'K320', legacyCode: 'KL-EU-3', codeRef: 'K-EU-LeasinghvidpladebilDelvisFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Leasing af hvidpladebil i min. 6 mdr.  Udlandet (faktura x pro rata)', deductible: 'Maks 25% af særligt fradrags-grundlag', reportingRule: 'Rubrik A - ydelser +  Moms af ydelseskøb i udlandet med omvendt betalingspligt og Købsmoms (indgående moms)', guidance: 'Denne kode anvendes af virksomheder med både momsfri og momspligtige aktiviteter ved leasing af hvidpladebiler i andre EU-lande i perioder længere ind 6 mdr, hvor bilen anvendes min. 10 pct. i forbind' },
{ standardCode: 'K330', legacyCode: 'K-EU-Y-L1', codeRef: 'K-EU-Y-GulpladebilFradragPrivat', alphaFlowCode: null, rate: 25, group: 'Køb fra EU-lande', heading: 'Leasing af gulpladebil fra udenlandsk leasinggiver, (private og blandede formål samt erhverv)', deductible: '0.333', reportingRule: 'Rubrik A - ydelser + Moms af ydelseskøb i udlandet med omvendt betalingspligt samt Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved leje af varebiler (med tilladt totalvægt på ikke over 3t) i andre EU-lande, når disse ikke udelukkende anvendes i virksomheden. Der kan fradrages 1/3 af den beregnede moms.' },
{ standardCode: 'K340', legacyCode: 'K-EU-MF', codeRef: 'K-EU-Momsfritaget', alphaFlowCode: null, rate: 0, group: 'Køb fra EU-lande', heading: 'Momsfritagede køb af varer og ydelser (EU)', deductible: '', reportingRule: 'Skal ikke medtages i angivelsen', guidance: 'Denne kode anvendes ved køb af momsfritagne ydelser i andre lande. Det kan eksempelvis være finansielle ydelser, hospitalsydelser eller lignende.' },
{ standardCode: 'K410', legacyCode: 'K-%EU-V-1', codeRef: 'K-%EU-V-Fradrag', alphaFlowCode: 'KUF', rate: 25, group: 'Køb fra lande udenfor EU', heading: 'Varekøb, Importmoms (% EU), fuldt fradragsberettiget (100%)', deductible: '1', reportingRule: 'Moms af varekøb i udlandet (både EU og lande uden for EU) og Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved varekøb uden moms i lande udenfor EU, hvor virksomheden har fuldt fradrag for den afregnede importmoms.' },
{ standardCode: 'K420', legacyCode: 'K-%EU-V-3', codeRef: 'K-%EU-V-SkønsmæssigFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra lande udenfor EU', heading: 'Varekøb, importmoms (% EU), skønsmæssigt fradrag', deductible: 'Skøn', reportingRule: 'Moms af varekøb i udlandet (både EU og lande uden for EU) og Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved varekøb uden moms i lande udenfor EU, hvor den indkøbte vare både anvendes i forbindelse med de momspligtige aktiviteter og til formål der er virksomheden uvedkommende og hvor' },
{ standardCode: 'K430', legacyCode: 'K-%EU-V-0', codeRef: 'K-%EU-V-IngenFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra lande udenfor EU', heading: 'Varekøb, importmoms (% EU), ingen fradrag', deductible: '', reportingRule: 'Moms af varekøb i udlandet (både EU og lande uden for EU)', guidance: 'Denne kode  anvendes ved varekøb uden moms i lande udenfor EU, hvor virksomheden ikke har adgang til fradrag for den afregnede importmoms, f.eks. fordi de indkøbte varer ikke anvendes i forbindelse me' },
{ standardCode: 'K440', legacyCode: 'K-%EU-V-2', codeRef: 'K-%EU-V-DelvisFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra lande udenfor EU', heading: 'Varekøb, importmoms (% EU), Delvis fradrag (pro rata)', deductible: 'Delvis', reportingRule: 'Moms af varekøb i udlandet (både EU og lande uden for EU) og Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved varekøb uden moms i lande udenfor EU, hvor den indkøbte vare både anvendes i forbindelse med de momspligtige og de momsfrie aktiviteter og hvor retten til fradrag for den afre' },
{ standardCode: 'K450', legacyCode: 'K-%EU-V-4', codeRef: 'K-%EU-V-ArealFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra lande udenfor EU', heading: 'Varekøb, importmoms (% EU), Arealbaseret fradragsret fast ejendom', deductible: 'Arealfordeling', reportingRule: 'Moms af varekøb i udlandet (både EU og lande uden for EU) og Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved varekøb uden moms i lande udenfor EU, når købet vedrører opførelse, ombygning, reparation og vedligeholdelse af bygninger, når bygningen også omfatter lokaler der vedrører and' },
{ standardCode: 'K460', legacyCode: 'K-%EU-Y-1', codeRef: 'K-%EU-Y-Fradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra lande udenfor EU', heading: 'Ydelseskøb, omvendt betalingspligt (% EU), fuldt fradragsberettiget (100%)', deductible: '1', reportingRule: 'Moms af ydelseskøb i udlandet med omvendt betalingspligt og Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved ydelseskøb uden moms i lande udenfor EU, hvor virksomheden har fuldt fradrag for den beregnede tmoms.' },
{ standardCode: 'K470', legacyCode: 'K-%EU-Y-3', codeRef: 'K-%EU-DK-Y-SkønsmæssigFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra lande udenfor EU', heading: 'Ydelseskøb, omvendt betalingspligt (% EU), skønsmæssigt fradrag', deductible: 'Skøn', reportingRule: 'Moms af ydelseskøb i udlandet med omvendt betalingspligt og Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved ydelseskøb uden moms i lande udenfor EU, hvor den indkøbte ydelse både anvendes i forbindelse med de momspligtige aktiviteter og til formål der er virksomheden uvedkommende og' },
{ standardCode: 'K480', legacyCode: 'K-%EU-Y-0', codeRef: 'K-%EU-Y-IngenFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra lande udenfor EU', heading: 'Ydelseskøb, omvendt betalingspligt (% EU), ingen fradrag', deductible: '', reportingRule: 'Moms af ydelseskøb i udlandet med omvendt betalingspligt', guidance: 'Denne kode  anvendes ved ydelseskøb uden moms i lande udenfor EU, hvor virksomheden ikke har adgang til fradrag for den beregnede moms, f.eks. fordi de indkøbte ydelser ikke anvendes i forbindelse med' },
{ standardCode: 'K490', legacyCode: 'K-%EU-Y-2', codeRef: 'K-%EU-Y-DelvisFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra lande udenfor EU', heading: 'Ydelseskøb, omvendt betalingspligt (% EU), Delvis fradrag', deductible: 'Delvis', reportingRule: 'Moms af ydelseskøb i udlandet med omvendt betalingspligt og Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved ydelseskøb uden moms i lande udenfor EU, hvor den indkøbte ydelse både anvendes i forbindelse med de momspligtige og de momsfrie aktiviteter og hvor retten til fradrag for den' },
{ standardCode: 'K500', legacyCode: 'K-%EU-Y-4', codeRef: 'K-%EU-Y-ArealFradrag', alphaFlowCode: null, rate: 25, group: 'Køb fra lande udenfor EU', heading: 'Ydelseskøb, omvendt betalingspligt (% EU), Arealbaseret fradragsret fast ejendom', deductible: 'Arealfordeling', reportingRule: 'Moms af ydelseskøb i udlandet med omvendt betalingspligt og Købsmoms (indgående moms)', guidance: 'Denne kode  anvendes ved ydelseskøb uden moms i lande udenfor EU, når købet vedrører opførelse, ombygning, reparation og vedligeholdelse af bygninger, når bygningen også omfatter lokaler der vedrører ' },
{ standardCode: 'S89', legacyCode: 'S12', codeRef: 'S-DK-12', alphaFlowCode: 'S12', rate: 12, group: 'Salg', heading: 'Momspligtige salg (DK), 12% moms (aviser, blade, persontransport)', deductible: '', reportingRule: 'Salgsmoms (udgående moms)', guidance: 'Denne kode anvendes ved salg med nedsat momsats på 12% (f.eks. aviser, blade, persontransport, adgangsbilletter til kulturarrangementer).' },
{ standardCode: 'K99', legacyCode: 'K12', codeRef: 'K-DK-12-Fradrag', alphaFlowCode: 'K12', rate: 12, group: 'Køb', heading: 'Indgående moms (DK), 12% moms, fuld fradrag (100%)', deductible: '1', reportingRule: 'Købsmoms (indgående moms)', guidance: 'Denne kode anvendes ved køb med 12% momsats.' },];

/**
 * Map en AlphaFlow intern momskode til den officielle SAF-T standardkode.
 * Returnerer "S01" for "S25", "K010" for "K25", etc.
 * Returnerer null hvis koden ikke har en officiel mapping (f.eks. "NONE").
 */
export function getStandardTaxCode(alphaFlowCode: string): string | null {
  const entry = SAFT_VAT_CODES.find((c) => c.alphaFlowCode === alphaFlowCode);
  return entry?.standardCode ?? null;
}

/**
 * Map en AlphaFlow intern momskode til den fulde SaftVatCode-post.
 */
export function getSaftVatCode(alphaFlowCode: string): SaftVatCode | null {
  return SAFT_VAT_CODES.find((c) => c.alphaFlowCode === alphaFlowCode) ?? null;
}

/**
 * Returner alle momskoder der er relevante for SAF-T-eksport
 * (kun dem der har en alphaFlowCode mapping — de 7 der bruges i systemet).
 */
export function getMappedSaftVatCodes(): SaftVatCode[] {
  return SAFT_VAT_CODES.filter((c) => c.alphaFlowCode !== null);
}

/**
 * Find en momskode ud fra dens officielle standardkode.
 * Bruges f.eks. når man vil slå vejledning/description op for en given kode.
 */
export function getSaftVatCodeByStandardCode(standardCode: string): SaftVatCode | null {
  return SAFT_VAT_CODES.find((c) => c.standardCode === standardCode) ?? null;
}
