/**
 * AlphaFlow — Tink Open Banking API Client
 *
 * Full integration with Tink's API for:
 *   - Building the Tink Link authorization URL (OAuth2 Authorization Code flow)
 *   - Exchanging authorization code for access token
 *   - Listing user's bank accounts
 *   - Fetching transactions for a specific account
 *   - Refreshing access tokens via credentials re-authorization
 *   - Revoking bank credentials (disconnecting)
 *
 * Works in both SANDBOX and PRODUCTION modes.
 * Sandbox: Uses Tink's sandbox environment with test credentials.
 *   - Set TINK_CLIENT_ID and TINK_CLIENT_SECRET to your sandbox values.
 *   - Tink Link will show a test bank selection (no real bank login needed).
 *   - Transactions are mock data generated by Tink.
 *
 * Production: Uses real bank connections.
 *   - Set TINK_CLIENT_ID and TINK_CLIENT_SECRET to production values.
 *   - Users authenticate with their real bank via Tink Link.
 *
 * Tink API docs: https://docs.tink.com/api
 *
 * Environment variables (all optional — when not set, the Tink provider
 * in bank-providers.ts falls back to sandbox mock mode):
 *   TINK_CLIENT_ID      — OAuth2 client ID from Tink Console
 *   TINK_CLIENT_SECRET  — OAuth2 client secret from Tink Console
 *   TINK_REDIRECT_URI   — Callback URI registered in Tink Console
 *                          Defaults to {APP_URL}/api/bank-connections/tink-callback
 */

import { logger } from '@/lib/logger';

// ─── Types ──────────────────────────────────────────────────────────────

/** Configuration read from environment variables */
export interface TinkConfig {
  clientId: string;
  clientSecret: string;
  redirectUri: string;
  /** Base URL for the Tink API (same for sandbox and production) */
  apiBaseUrl: string;
  /** Base URL for Tink Link (the hosted authorization UI) */
  linkBaseUrl: string;
  /** Market code — Denmark for AlphaFlow */
  market: string;
  /** Locale for Tink Link UI */
  locale: string;
}

/** OAuth2 token response from Tink */
export interface TinkTokenResponse {
  access_token: string;
  token_type: 'bearer';
  expires_in: number;
  scope: string;
}

/** A single bank account from Tink */
export interface TinkAccount {
  /** Tink's internal account ID — used for transaction fetches */
  id: string;
  /** The account name given by the user or bank */
  name: string;
  /** Account type (CHECKING, SAVINGS, etc.) */
  type: string;
  /** Available balance in the account's currency */
  balances: Array<{
    amount: number;
    currencyCode: string;
  }>;
  /** Bank identifier (e.g., "nordea-dk", "danskebank-dk") */
  holderName?: string;
  /** The bank this account belongs to */
  credentialsId: string;
  /** Bank display name */
  institution: {
    name: string;
  };
  /** Account number in the bank's format */
  accountNumber?: string;
  /** IBAN if available */
  iban?: string;
}

/** A single transaction from Tink */
export interface TinkTransaction {
  /** Tink's internal ID for this transaction */
  id: string;
  /** ISO 8601 date (YYYY-MM-DD) when the transaction was posted/booked */
  date: string;
  /** Free-text description from the bank statement */
  description: string;
  /** Original amount in the account's currency. Negative = debit, positive = credit */
  amount: number;
  /** Running balance after this transaction (may not be present for all banks) */
  balance?: number;
  /** Currency code (ISO 4217) */
  currencyCode: string;
  /** Merchant/display name if available */
  merchantName?: string;
  /** Category information if available */
  category?: string;
  /** Pending flag — true if transaction is not yet fully booked */
  pending: boolean;
}

/** Transaction list response from Tink */
export interface TinkTransactionsResponse {
  transactions: TinkTransaction[];
  /** Cursor for paginating to the next page of results */
  nextPageToken?: string;
  /** Total number of transactions matching the query */
  totalTransactions?: number;
}

/** Credential info from Tink (for re-authorization) */
export interface TinkCredential {
  id: string;
  providerName: string;
  status: 'AUTHENTICATED' | 'UPDATED' | 'TEMPORARY_ERROR' | 'PERMANENT_ERROR' | 'AUTHENTICATION_ERROR' | 'SESSION_EXPIRED';
  type: string;
}

// ─── Configuration ──────────────────────────────────────────────────────

/**
 * Read Tink configuration from environment variables.
 * Returns null if the minimum required config (CLIENT_ID + CLIENT_SECRET) is missing.
 */
export function getTinkConfig(): TinkConfig | null {
  const clientId = process.env.TINK_CLIENT_ID;
  const clientSecret = process.env.TINK_CLIENT_SECRET;

  if (!clientId || !clientSecret) {
    return null;
  }

  const appUrl = process.env.APP_URL || 'http://localhost:3000';
  const redirectUri = process.env.TINK_REDIRECT_URI || `${appUrl}/api/bank-connections/tink-callback`;

  return {
    clientId,
    clientSecret,
    redirectUri,
    // Tink uses the same API base URL for both sandbox and production.
    // The sandbox vs production behavior is controlled by the client_id/secret.
    apiBaseUrl: process.env.TINK_API_BASE_URL || 'https://api.tink.com',
    linkBaseUrl: process.env.TINK_LINK_BASE_URL || 'https://link.tink.com',
    market: process.env.TINK_MARKET || 'DK',
    locale: process.env.TINK_LOCALE || 'da_DK',
  };
}

// ─── Tink Link Authorization URL ────────────────────────────────────────

/**
 * Build the Tink Link authorization URL.
 *
 * Tink Link is Tink's hosted authorization UI where the user:
 *   1. Selects their bank
 *   2. Authenticates with their bank credentials
 *   3. Grants access to the requested scopes
 *
 * After successful authorization, Tink redirects to the `redirectUri`
 * with `code` and `state` query parameters.
 *
 * @param config - Tink configuration
 * @param state  - Opaque state string passed back in the redirect.
 *                 Should contain the BankConnection ID so the callback
 *                 can update the correct connection record.
 * @param scopes - Array of Tink API scopes to request. Defaults to
 *                 accounts:read, balances:read, transactions:read, credentials:read
 * @returns The full Tink Link URL to redirect the user to
 */
export function buildTinkLinkUrl(
  config: TinkConfig,
  state: string,
  scopes: string[] = [
    'accounts:read',
    'balances:read',
    'transactions:read',
    'credentials:read',
  ],
): string {
  const params = new URLSearchParams({
    client_id: config.clientId,
    redirect_uri: config.redirectUri,
    scope: scopes.join(' '),
    market: config.market,
    locale: config.locale,
    state,
    // Show the account selection screen after bank authentication
    // so the user can choose which accounts to connect
    iframe_test: 'true',
  });

  return `${config.linkBaseUrl}/1.0/authorize?${params.toString()}`;
}

// ─── OAuth2 Token Exchange ──────────────────────────────────────────────

/**
 * Exchange an authorization code (from Tink Link callback) for an access token.
 *
 * This is a server-to-server call using client_credentials or authorization_code
 * grant type. The access token is used for all subsequent Tink API calls.
 *
 * Tink access tokens are short-lived (~30 minutes). Store the credentialsId
 * from the accounts response to enable re-authorization without full user
 * re-authentication.
 *
 * @param config - Tink configuration
 * @param code   - Authorization code from the Tink Link redirect
 * @returns Token response with access_token and metadata
 * @throws Error if the exchange fails
 */
export async function exchangeCodeForToken(
  config: TinkConfig,
  code: string,
): Promise<TinkTokenResponse> {
  const tokenUrl = `${config.apiBaseUrl}/api/v1/oauth/token`;

  const params = new URLSearchParams({
    grant_type: 'authorization_code',
    code,
    client_id: config.clientId,
    client_secret: config.clientSecret,
    redirect_uri: config.redirectUri,
  });

  const response = await fetch(tokenUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: params.toString(),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    logger.error('Tink token exchange failed', {
      status: response.status,
      body: errorBody,
    });
    throw new Error(
      `Tink token exchange failed (${response.status}): ${errorBody}`
    );
  }

  const data = await response.json() as TinkTokenResponse;
  logger.info('Tink token exchanged successfully', {
    expiresIn: data.expires_in,
    scope: data.scope,
  });

  return data;
}

// ─── Accounts ───────────────────────────────────────────────────────────

/**
 * List all bank accounts the user has connected through Tink.
 *
 * Returns accounts from all banks the user has authorized.
 * Each account includes balances, account numbers, and the
 * credentialsId needed for re-authorization.
 *
 * @param config       - Tink configuration
 * @param accessToken  - Valid access token from exchangeCodeForToken()
 * @returns Array of Tink accounts
 * @throws Error if the API call fails or token is invalid
 */
export async function listAccounts(
  config: TinkConfig,
  accessToken: string,
): Promise<TinkAccount[]> {
  const url = `${config.apiBaseUrl}/api/v1/accounts/list`;

  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const errorBody = await response.text();
    logger.error('Tink list accounts failed', {
      status: response.status,
      body: errorBody,
    });
    throw new Error(
      `Tink list accounts failed (${response.status}): ${errorBody}`
    );
  }

  const data = await response.json() as { accounts: TinkAccount[] };
  logger.info('Tink accounts fetched', {
    count: data.accounts?.length ?? 0,
  });

  return data.accounts || [];
}

// ─── Transactions ───────────────────────────────────────────────────────

/**
 * Fetch transactions for a specific bank account.
 *
 * Supports date-range filtering and pagination via page tokens.
 * Transactions are returned in reverse chronological order (newest first).
 *
 * Tink transaction amounts:
 *   - Positive = credit (money in)
 *   - Negative = debit (money out)
 *
 * @param config       - Tink configuration
 * @param accessToken  - Valid access token
 * @param accountId    - Tink's internal account ID (from listAccounts)
 * @param options      - Optional date range and pagination
 * @returns Transaction list response with pagination cursor
 * @throws Error if the API call fails
 */
export async function fetchAccountTransactions(
  config: TinkConfig,
  accessToken: string,
  accountId: string,
  options?: {
    fromDate?: Date;
    toDate?: Date;
    pageSize?: number;
    pageToken?: string;
  },
): Promise<TinkTransactionsResponse> {
  const url = new URL(`${config.apiBaseUrl}/api/v1/data/transactions`);

  const params = url.searchParams;
  params.set('accountId', accountId);

  if (options?.fromDate) {
    params.set('startDate', options.fromDate.toISOString().split('T')[0]);
  }
  if (options?.toDate) {
    params.set('endDate', options.toDate.toISOString().split('T')[0]);
  }
  if (options?.pageSize) {
    params.set('pageSize', String(Math.min(options.pageSize, 1000)));
  }
  if (options?.pageToken) {
    params.set('pageToken', options.pageToken);
  }

  const response = await fetch(url.toString(), {
    method: 'GET',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const errorBody = await response.text();
    logger.error('Tink fetch transactions failed', {
      status: response.status,
      accountId,
      body: errorBody,
    });
    throw new Error(
      `Tink fetch transactions failed (${response.status}): ${errorBody}`
    );
  }

  const data = await response.json() as TinkTransactionsResponse;
  return data;
}

/**
 * Fetch ALL transactions for an account (handles pagination automatically).
 *
 * @param config       - Tink configuration
 * @param accessToken  - Valid access token
 * @param accountId    - Tink's internal account ID
 * @param options      - Optional date range
 * @returns Flat array of all transactions
 */
export async function fetchAllTransactions(
  config: TinkConfig,
  accessToken: string,
  accountId: string,
  options?: {
    fromDate?: Date;
    toDate?: Date;
  },
): Promise<TinkTransaction[]> {
  const allTransactions: TinkTransaction[] = [];
  let pageToken: string | undefined;

  do {
    const page = await fetchAccountTransactions(config, accessToken, accountId, {
      ...options,
      pageSize: 500,
      pageToken,
    });

    allTransactions.push(...(page.transactions || []));
    pageToken = page.nextPageToken;

    // Safety: stop after 20 pages (10,000 transactions) to prevent infinite loops
    if (allTransactions.length > 10000) {
      logger.warn('Tink transaction fetch hit 10k limit, truncating');
      break;
    }
  } while (pageToken);

  return allTransactions;
}

// ─── Credentials (for token refresh / re-authorization) ─────────────────

/**
 * Get stored credentials for the current user.
 *
 * Credentials represent the user's bank login sessions stored by Tink.
 * Each credential has a status and can be used to re-authorize
 * without requiring the user to re-enter their bank credentials.
 *
 * @param config       - Tink configuration
 * @param accessToken  - Valid access token
 * @returns Array of credentials
 */
export async function listCredentials(
  config: TinkConfig,
  accessToken: string,
): Promise<TinkCredential[]> {
  const url = `${config.apiBaseUrl}/api/v1/credentials`;

  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
    },
  });

  if (!response.ok) {
    const errorBody = await response.text();
    logger.error('Tink list credentials failed', {
      status: response.status,
      body: errorBody,
    });
    throw new Error(
      `Tink list credentials failed (${response.status}): ${errorBody}`
    );
  }

  const data = await response.json() as { credentials: TinkCredential[] };
  return data.credentials || [];
}

/**
 * Re-authorize a credential (get a new access token without full user authentication).
 *
 * This is useful when the access token has expired but the user's bank
 * session is still valid on Tink's side. The credential status determines
 * whether re-authorization is possible:
 *
 *   - AUTHENTICATED / UPDATED: Can re-authorize
 *   - SESSION_EXPIRED / TEMPORARY_ERROR: May need user interaction
 *   - PERMANENT_ERROR: Must re-authenticate through Tink Link
 *
 * @param config        - Tink configuration
 * @param accessToken   - A valid access token (from a recent authorization)
 * @param credentialsId - The credential ID to re-authorize
 * @returns A new authorization code that can be exchanged for a fresh access token
 */
export async function reauthorizeCredential(
  config: TinkConfig,
  accessToken: string,
  credentialsId: string,
): Promise<string> {
  const url = `${config.apiBaseUrl}/api/v1/credentials/${credentialsId}/authorize`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      redirectUri: config.redirectUri,
      state: `reauth-${credentialsId}`,
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    logger.error('Tink re-authorize credential failed', {
      status: response.status,
      credentialsId,
      body: errorBody,
    });
    throw new Error(
      `Tink re-authorize failed (${response.status}): ${errorBody}`
    );
  }

  const data = await response.json() as { authorizationCode: string };
  return data.authorizationCode;
}

/**
 * Revoke/delete a credential, effectively disconnecting the user's bank.
 *
 * After revocation, Tink will no longer have access to the user's
 * bank data for this credential. The user must re-authenticate
 * through Tink Link to reconnect.
 *
 * @param config        - Tink configuration
 * @param accessToken   - Valid access token
 * @param credentialsId - The credential ID to revoke
 */
export async function deleteCredential(
  config: TinkConfig,
  accessToken: string,
  credentialsId: string,
): Promise<void> {
  const url = `${config.apiBaseUrl}/api/v1/credentials/${credentialsId}`;

  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
    },
  });

  if (!response.ok && response.status !== 204) {
    const errorBody = await response.text();
    logger.error('Tink delete credential failed', {
      status: response.status,
      credentialsId,
      body: errorBody,
    });
    throw new Error(
      `Tink delete credential failed (${response.status}): ${errorBody}`
    );
  }

  logger.info('Tink credential revoked', { credentialsId });
}

// ─── Helpers ────────────────────────────────────────────────────────────

/**
 * Check if a Tink access token is likely expired.
 *
 * Tink tokens expire in ~30 minutes. If we don't store the exact expiry,
 * we use a conservative heuristic: if the connection was last synced more
 * than 25 minutes ago, consider the token expired.
 *
 * @param lastSyncAt - When the connection was last successfully synced
 * @returns true if the token should be considered expired
 */
export function isTokenLikelyExpired(lastSyncAt: Date | null): boolean {
  if (!lastSyncAt) return true;
  const TOKEN_LIFETIME_MS = 25 * 60 * 1000; // 25 minutes (conservative)
  return Date.now() - lastSyncAt.getTime() > TOKEN_LIFETIME_MS;
}

/**
 * Convert a Tink account to a format compatible with BankTransaction interface.
 * Extracts the primary balance from the account.
 */
export function extractAccountBalance(account: TinkAccount): number | null {
  if (!account.balances || account.balances.length === 0) return null;
  // Prefer "available" balance; fall back to the first balance
  return account.balances[0]?.amount ?? null;
}