// ============================================================
// boot.ts — Prisma auto-generate + service start
// ============================================================
// PM2 runs: `bun boot.ts` (instead of `bun index.ts`)
//
// This wrapper ensures the Prisma client is generated before
// the service imports @prisma/client. Bun does NOT run
// postinstall scripts by default, so `prisma generate` from
// package.json often never executes on the server.
//
// IMPORTANT: This file must NOT use top-level await, because
// PM2's ProcessContainerForkBun.js uses require() to load it,
// and require() cannot handle async ESM modules.
// ============================================================

import { existsSync, readFileSync } from 'fs'
import { execSync } from 'child_process'
import { resolve, dirname } from 'path'

const __dirname = dirname(new URL(import.meta.url).pathname)
const clientPath = resolve(__dirname, 'node_modules/.prisma/client')
const schemaPath = resolve(__dirname, '../../prisma/schema.prisma')

// ── Validate existing Prisma client ──────────────────────────
// The "Prisma client found" message in previous versions was
// unreliable — require() can succeed even when the generated
// client is incompatible with the @prisma/client runtime.
// This happens when @prisma/client and prisma CLI versions
// don't match (e.g., @prisma/client@6.11.x vs prisma@6.19.2).
//
// We now check version alignment between the runtime and the
// generated client. If they don't match, we force regeneration.
let clientReady = false
try {
  const clientIndex = resolve(clientPath, 'index.js')
  if (existsSync(clientIndex)) {
    // Check version alignment: read @prisma/client runtime version
    // and compare with the generated client's embedded version.
    const runtimePkgPath = resolve(__dirname, 'node_modules/@prisma/client/package.json')
    const generatedPkgPath = resolve(clientPath, 'package.json')

    let runtimeVersion = 'unknown'
    let generatedVersion = 'unknown'

    if (existsSync(runtimePkgPath)) {
      try {
        runtimeVersion = JSON.parse(readFileSync(runtimePkgPath, 'utf-8')).version || 'unknown'
      } catch { /* ignore */ }
    }

    // The generated client embeds its prisma version in the default.js file.
    // We can also check the engine hash for mismatch detection.
    // For simplicity, compare the major.minor.patch of the runtime
    // with what prisma CLI generated. The generated client's package.json
    // sometimes has a version — check it.
    if (existsSync(generatedPkgPath)) {
      try {
        generatedVersion = JSON.parse(readFileSync(generatedPkgPath, 'utf-8')).version || 'unknown'
      } catch { /* ignore */ }
    }

    // If versions are both readable and match, the client is likely OK.
    // If we can't determine versions, fall through to try require().
    if (runtimeVersion !== 'unknown' && generatedVersion !== 'unknown' && runtimeVersion === generatedVersion) {
      clientReady = true
      console.log(`[Hermes Boot] Prisma client OK (v${runtimeVersion}) — skipping generate`)
    } else if (runtimeVersion !== 'unknown' && generatedVersion !== 'unknown' && runtimeVersion !== generatedVersion) {
      console.log(`[Hermes Boot] Prisma version mismatch: runtime=@prisma/client@${runtimeVersion}, generated=v${generatedVersion} — regenerating...`)
    } else {
      // Can't determine versions — try require() as a fallback.
      // If this throws, the client is corrupt.
      try {
        require(resolve(clientPath))
        clientReady = true
        console.log('[Hermes Boot] Prisma client found — skipping generate')
      } catch {
        console.log('[Hermes Boot] Existing Prisma client failed to load — regenerating...')
      }
    }
  }
} catch (err: any) {
  console.log(`[Hermes Boot] Prisma client validation error: ${err.message} — regenerating...`)
}

if (!clientReady) {
  console.log('[Hermes Boot] Running prisma generate...')
  try {
    // Use bunx (not npx) since we're running under Bun.
    // bunx prefers locally-installed packages.
    execSync(`bunx prisma generate --schema="${schemaPath}"`, {
      stdio: 'inherit',
      cwd: __dirname,
      timeout: 60_000,
    })
    console.log('[Hermes Boot] Prisma client generated successfully')
  } catch (err) {
    console.error('[Hermes Boot] prisma generate failed! The service may not work correctly.')
    console.error('[Hermes Boot] Try running manually: cd mini-services/hermes-agent && bunx prisma generate --schema=../../prisma/schema.prisma')
    // Don't exit — the service might still work with MockTenantProvider
    // or the client may have been generated by a previous run
  }
}

// Import and start the real service.
// CRITICAL: Use an IIFE, NOT top-level await.
// PM2's ProcessContainerForkBun.js uses require() to load this file,
// and require() cannot handle async ESM modules (top-level await).
;(async () => {
  await import('./index')
})().catch(err => {
  console.error('[Hermes Boot] Fatal startup error:', err)
  process.exit(1)
})
